import { describe, expect, test } from "bun:test";
import { BALANCE_PROFILES } from "../common/balance";
import { bucklerBlockCost, healingCast, healingCooldown, healingFraction, rollWeaponDamage, skillCooldown, skillRange, weaponAttackSpeed, weaponRange, weaponUsesProjectile } from "../common/combat";
import { collectIntoInventory, emptyScraps, equipFromInventory, extractableSkills, extractFromInventory, inventoryCapacity, isEquippedTile, occupiedInventorySlots, purgeFromInventory, sellFromInventory, upgradeCosts, upgradeFromInventory } from "../common/inventory";
import { generateBuckler, generateItem, generateRelic, itemStackKey, levelUpItem, MAX_ITEM_LEVEL, starterClub } from "../common/items";
import { cumulativeXpForLevel, DEFAULT_ALLOCATION, derivedStats, lerpXpDisplay, levelForXp, xpForNextLevel, ZERO_STATS } from "../common/progression";
import { parseClientMessage, type PlayerProgress } from "../common/protocol";
import { SeededRandom } from "../common/random";
import { regularCount, regularLevel, rivalLevel, rivalXpReward } from "../common/waves";
import { WEAPONS, SKILLS } from "../common/content";
import { effectiveSkillLevel, forceField } from "../src/game/systems/HeroCombatSystem";
import { formatPreviewValue, previewTone } from "../src/ui/preview";
import { gameSocketUrl } from "../src/net/SocketClient";

function progress(): PlayerProgress { return { level: 0, xp: 0, stats: { ...ZERO_STATS }, allocation: { ...DEFAULT_ALLOCATION }, gold: 1000, souls: 0, scraps: emptyScraps(), mainHand: starterClub(), inventoryTiles: [], learnedSkills: ["healing"], learnedSkillLevels: { healing: 1 }, universalSkills: ["healing"] }; }
let id = 0;

describe("balance and waves", () => {
  test("keeps capped waves and player-independent rival scaling", () => { const balance = BALANCE_PROFILES.normal; expect(regularCount(1, balance)).toBe(12); expect(regularLevel(3, 0, 16, balance)).toBe(1); expect(rivalLevel(1, balance)).toBe(1); expect(rivalLevel(5, balance)).toBe(3); expect(rivalXpReward(3)).toBe(34); expect(regularCount(100, balance)).toBe(40); });
  test("development does not accelerate combat or rewards", () => { const item = starterClub(); const normal = rollWeaponDamage(item, ZERO_STATS, "hero", BALANCE_PROFILES.normal, new SeededRandom(2)); expect(rollWeaponDamage(item, ZERO_STATS, "hero", BALANCE_PROFILES.dev, new SeededRandom(2))).toBeCloseTo(normal); expect(BALANCE_PROFILES.dev.rewards).toEqual(BALANCE_PROFILES.normal.rewards); });
});
describe("attack timing", () => { test("uses damped weight handling for physical and magic weapons", () => { const club = starterClub(); expect(weaponAttackSpeed(club, ZERO_STATS)).toBeCloseTo(10 / 12); expect(weaponAttackSpeed(club, { ...ZERO_STATS, agility: 100 })).toBeCloseTo(20 / 12); const generatedStaff = generateItem(0, "common", 5, { allowedClasses: ["staff"] }); const staff = { ...generatedStaff, modifiers: { ...generatedStaff.modifiers, attackSpeedMultiplier: 1 } }; expect(weaponAttackSpeed(staff, { ...ZERO_STATS, strength: 100, spirit: 100 })).toBeCloseTo(20 / 16); expect(weaponAttackSpeed(staff, { ...ZERO_STATS, agility: 1_000 })).toBeCloseTo(10 / 16); }); });
test("derives health from Strength and mana from Intelligence", () => { const base = derivedStats(ZERO_STATS); expect(base.maxHp).toBe(10); expect(base.maxMana).toBe(5); const advanced = derivedStats({ ...ZERO_STATS, strength: 3, magic: 99, intelligence: 2 }); expect(advanced.maxHp).toBe(13); expect(advanced.maxMana).toBe(9); });
describe("XP curve", () => { test("uses a quadratic cumulative curve with a 15 XP first level", () => { expect([0, 1, 2, 3, 4, 5].map(xpForNextLevel)).toEqual([15, 45, 75, 105, 135, 165]); expect(cumulativeXpForLevel(4)).toBe(240); expect(levelForXp(239)).toBe(3); expect(levelForXp(240)).toBe(4); }); });

describe("permanent inventory", () => {
  test("toggles an equipped offhand back to unequipped", () => { const state = progress(); const buckler = { ...generateBuckler(0, "common", 12), requirements: {} }; collectIntoInventory(state, buckler, () => `tile-${++id}`, () => ++id); const tile = state.inventoryTiles[0]; expect(equipFromInventory(state, tile.id).changed).toBeTrue(); expect(state.offHand).toBeDefined(); expect(equipFromInventory(state, tile.id).changed).toBeTrue(); expect(state.offHand).toBeUndefined(); expect(tile.quantity).toBe(1); });
  test("prices percentage return above one stamina and upgrades it toward one", () => { const base = { ...generateBuckler(0, "rare", 18), reflectionComponents: ["return" as const] }; const stats = { ...ZERO_STATS, agility: 50 }; const baseCost = bucklerBlockCost(base, stats); const upgraded = levelUpItem(base, 19); expect(baseCost).toBeGreaterThan(1); expect(bucklerBlockCost(upgraded, stats)).toBeGreaterThan(1); expect(bucklerBlockCost(upgraded, stats)).toBeLessThan(baseCost); });
  test("equips relics as offhands and preserves their attraction passive", () => { const state = progress(); const relic = { ...generateRelic(0, "rare", 12), attractionSpeed: 35 }; collectIntoInventory(state, relic, () => `tile-${++id}`, () => ++id); expect(equipFromInventory(state, state.inventoryTiles[0].id).changed).toBeTrue(); expect(state.offHand?.itemKind).toBe("relic"); expect(state.offHand?.attractionSpeed).toBe(35); });
  test("removes empty stacks and releases their capacity immediately", () => { const state = progress(); expect(inventoryCapacity(0)).toBe(4); for (let n = 0; n < 4; n += 1) expect(collectIntoInventory(state, generateItem(n, "common", 100 + n), () => `tile-${++id}`, () => ++id).changed).toBeTrue(); const tile = state.inventoryTiles[0]; purgeFromInventory(state, tile.id); expect(state.inventoryTiles.some((candidate) => candidate.id === tile.id)).toBeFalse(); expect(occupiedInventorySlots(state)).toBe(3); expect(collectIntoInventory(state, generateItem(9, "epic", 999), () => `tile-${++id}`, () => ++id).changed).toBeTrue(); expect(occupiedInventorySlots(state)).toBe(4); });
  test("upgrades one source copy without creating persistent automation", () => { const state = progress(); const item = generateItem(1, "common", 41); collectIntoInventory(state, item, () => `tile-${++id}`, () => ++id); collectIntoInventory(state, { ...item, id: "copy" }, () => `tile-${++id}`, () => ++id); state.scraps.common = 10; const gold = state.gold; const result = upgradeFromInventory(state, state.inventoryTiles[0].id, () => `tile-${++id}`, () => 55); expect(result.changed).toBeTrue(); expect(result.created?.level).toBe(2); expect(state.inventoryTiles[0].quantity).toBe(1); expect(state.inventoryTiles[1].quantity).toBe(1); expect(state.scraps.common).toBe(6); expect(state.gold).toBeLessThan(gold); });
  test("uses lower upgrade bases and increases them for direct attribute points", () => { const plain = generateItem(1, "common", 41); const attributed = { ...plain, statBonuses: { spirit: 3 } }; expect(upgradeCosts(plain)).toEqual({ gold: Math.ceil(plain.sellValue * 1.5), scraps: 4 }); expect(upgradeCosts(attributed)).toEqual({ gold: Math.ceil(plain.sellValue * 1.5 * 1.3), scraps: 6 }); });
  test("upgrades a lone equipped copy in place when resources are sufficient", () => { const state = progress(); const item = { ...generateItem(1, "common", 141), requirements: {} }; collectIntoInventory(state, item, () => `tile-${++id}`, () => ++id); const tile = state.inventoryTiles.find((candidate) => candidate.key === itemStackKey(item))!; expect(equipFromInventory(state, tile.id).changed).toBeTrue(); state.scraps.common = 20; const result = upgradeFromInventory(state, tile.id, () => `tile-${++id}`, () => 155); expect(result.changed).toBeTrue(); expect(state.mainHand.level).toBe(2); const upgraded = state.inventoryTiles.find((candidate) => candidate.key === itemStackKey(state.mainHand)); expect(upgraded?.quantity).toBe(1); expect(isEquippedTile(state, upgraded!)).toBeTrue(); expect(state.inventoryTiles.some((candidate) => candidate.id === tile.id)).toBeFalse(); });
  test("retains equipped copies and rejects destructive actions", () => { const state = progress(); const item = { ...generateItem(1, "rare", 71), requirements: {} }; collectIntoInventory(state, item, () => `tile-${++id}`, () => ++id); const tile = state.inventoryTiles[0]; expect(equipFromInventory(state, tile.id).changed).toBeTrue(); expect(tile.quantity).toBe(1); expect(isEquippedTile(state, tile)).toBeTrue(); expect(state.inventoryTiles.some((candidate) => candidate.key === itemStackKey(starterClub()))).toBeTrue(); const gold = state.gold; const scraps = state.scraps.rare; expect(sellFromInventory(state, tile.id).changed).toBeFalse(); expect(purgeFromInventory(state, tile.id).changed).toBeFalse(); expect(tile.quantity).toBe(1); expect(state.gold).toBe(gold); expect(state.scraps.rare).toBe(scraps); });
});

describe("protocol validation", () => { test("accepts v20 inventory, suicide, and anonymous commands and rejects retired automation", () => { expect(parseClientMessage({ type: "upgradeItem", tileId: "tile-1", bulk: true })).toEqual({ type: "upgradeItem", tileId: "tile-1", bulk: true }); expect(parseClientMessage({ type: "deferDrop", dropId: "drop-1" })).toEqual({ type: "deferDrop", dropId: "drop-1" }); expect(parseClientMessage({ type: "suicide" })?.type).toBe("suicide"); expect(parseClientMessage({ type: "join", name: "Hero_1" })?.type).toBe("join"); expect(parseClientMessage({ type: "join", name: "bad name" })).toBeUndefined(); expect(parseClientMessage({ type: "listHeroes" })?.type).toBe("listHeroes"); expect(parseClientMessage({ type: "respecStats", allocation: { agility: 1, strength: 1, magic: 1, spirit: 1, intelligence: 1 } })?.type).toBe("respecStats"); expect(parseClientMessage({ type: "setStackAutomation", tileId: "tile-1", mode: "sell", maxRarity: "rare" })).toBeUndefined(); expect(parseClientMessage({ type: "mergeItem", tileId: "tile-1" })).toBeUndefined(); expect(parseClientMessage({ type: "creepKilled", unitId: "unit-1", xpReward: 9999 })).toBeUndefined(); expect(parseClientMessage({ type: "updateAllocation", allocation: { agility: 5 } })).toBeUndefined(); }); });
describe("weapon skills", () => { test("gives every weapon class a distinct registered signature skill", () => { const skills = Object.values(WEAPONS).map((weapon) => weapon.skill); expect(new Set(skills).size).toBe(Object.keys(WEAPONS).length); for (const skill of skills) expect(skill && SKILLS[skill]).toBeDefined(); expect(WEAPONS.mace.skill).toBe("shockwave"); expect(WEAPONS.axe.skill).toBe("cleave"); expect(WEAPONS.hammer.skill).toBe("orbitingHammers"); expect(SKILLS.orbitingHammers.resource).toBe("mana"); }); });
describe("equipped skill levels", () => { test("temporarily adds one level and requires matching gear until universally unlocked", () => { const state = progress(); expect(effectiveSkillLevel(state, "bash")).toBe(1); state.learnedSkills.push("bash"); state.learnedSkillLevels.bash = 3; expect(effectiveSkillLevel(state, "bash")).toBe(4); state.mainHand = { ...state.mainHand, skills: [] }; expect(effectiveSkillLevel(state, "bash")).toBe(0); state.universalSkills.push("bash"); expect(effectiveSkillLevel(state, "bash")).toBe(3); const relic = generateRelic(1, "rare", 0); state.offHand = relic; expect(relic.skills).toContain("gravityPull"); expect(effectiveSkillLevel(state, "gravityPull")).toBe(1); }); });
describe("Epic skill extraction", () => { test("unlocks extracted skills for every weapon only at Epic rarity", () => { const rareState = progress(); const rare = generateItem(1, "rare", 17, { allowedClasses: ["staff"] }); rareState.inventoryTiles.push({ id: "rare", key: itemStackKey(rare), item: rare, quantity: 1 }); rareState.gold = 10_000; expect(extractFromInventory(rareState, "rare").changed).toBeTrue(); expect(rareState.learnedSkills).toContain("arcaneBolt"); expect(rareState.universalSkills).not.toContain("arcaneBolt"); const epicState = progress(); const epic = generateItem(1, "epic", 27, { allowedClasses: ["staff"] }); epicState.inventoryTiles.push({ id: "epic", key: itemStackKey(epic), item: epic, quantity: 1 }); epicState.gold = 10_000; expect(extractFromInventory(epicState, "epic").changed).toBeTrue(); expect(epicState.universalSkills).toEqual(expect.arrayContaining(["arcaneBolt", "frostOrb"])); }); });
test("does not charge or consume equipment with only reactive Blocking", () => { const state = progress(); const buckler = generateBuckler(1, "common", 12); state.inventoryTiles.push({ id: "buckler", key: itemStackKey(buckler), item: buckler, quantity: 1 }); const gold = state.gold; expect(extractableSkills(buckler)).toEqual([]); expect(extractFromInventory(state, "buckler")).toMatchObject({ changed: false, reason: "That item has no extractable skill." }); expect(state.gold).toBe(gold); expect(state.inventoryTiles[0].quantity).toBe(1); });
describe("spell resources", () => { test("registers Rent as life and buckler blocking as stamina", () => { expect(SKILLS.rent.resource).toBe("life"); expect(SKILLS.blocking.resource).toBe("stamina"); expect(generateBuckler(0, "common", 12).skills).toEqual(["blocking"]); }); });
test("grants Gold gain and rarity boost on bucklers by rarity", () => { const common = generateBuckler(1, "common", 12); const epic = generateBuckler(1, "epic", 12); expect(common.modifiers.goldGain).toBeCloseTo(0.05); expect(common.modifiers.rarityBoost).toBeCloseTo(0.02); expect(epic.modifiers.goldGain).toBeGreaterThan(common.modifiers.goldGain); expect(epic.modifiers.rarityBoost).toBeGreaterThan(common.modifiers.rarityBoost); });
describe("Force Field", () => { test("applies inward or outward velocity and interrupts attacks", () => { let interrupted = 0; const pulled = { position: { x: 100, y: 0 }, velocity: { x: 0, y: 0 }, interruptAttack: () => interrupted += 1 }; forceField(pulled, { x: 0, y: 0 }, 40, "pull"); expect(pulled.position).toEqual({ x: 100, y: 0 }); expect(pulled.velocity).toEqual({ x: -40, y: 0 }); const pushed = { position: { x: 100, y: 0 }, velocity: { x: 0, y: 0 } }; forceField(pushed, { x: 0, y: 0 }, 40, "push"); expect(pushed.velocity).toEqual({ x: 40, y: 0 }); expect(interrupted).toBe(1); expect(SKILLS.gravityPull.label).toBe("Force Field"); }); });
describe("extractable offhand and staff skills", () => {
  test("adds Force Field to attracting relics and high-rarity skills to spiked bucklers and staves", () => {
    const relic = Array.from({ length: 50 }, (_, seed) => generateRelic(1, "rare", seed)).find((item) => item.attractionSpeed > 0)!;
    const buckler = Array.from({ length: 100 }, (_, seed) => generateBuckler(1, "rare", seed)).find((item) => item.reflectionComponents.length > 0)!;
    const staff = generateItem(1, "rare", 17, { allowedClasses: ["staff"] });
    expect(relic.skills).toContain("gravityPull"); expect(buckler.skills).toEqual(expect.arrayContaining(["blocking", "thorns", "reflectiveSurge"])); expect(staff.skills).toEqual(expect.arrayContaining(["arcaneBolt", "frostOrb"]));
    expect(SKILLS.gravityPull.cooldown).toBe(18); expect(SKILLS.frostOrb.cooldown).toBe(20);
  });
});
describe("throwing axes", () => { test("generates a one-handed short-ranged projectile weapon with inherent bleed", () => { const axe = generateItem(0, "common", 17, { allowedClasses: ["throwingAxe"] }); expect(axe.hands).toBe(1); expect(axe.skills).toEqual(["rendingThrow"]); expect(axe.modifiers.bleedChance).toBeGreaterThanOrEqual(0.15); expect(weaponRange(axe)).toBe(210); expect(weaponUsesProjectile(axe)).toBeTrue(); }); });
describe("item sustain", () => { test("scales rolled sustain passives through upgrades", () => { const vampiric = generateItem(2, "rare", 8); expect(vampiric.modifiers.lifeStealBase).toBeCloseTo(0.021); const upgraded = levelUpItem(vampiric, 2); expect(upgraded.modifiers.lifeStealBase).toBeGreaterThan(vampiric.modifiers.lifeStealBase); expect(upgraded.modifiers.strengthRegenMultiplier).toBe(0); }); });
describe("equipment rarity promotion", () => {
  test("caps generated levels and promotes capped equipment to level one", () => { expect(generateItem(99, "common", 3).level).toBe(MAX_ITEM_LEVEL.common); expect(generateBuckler(99, "uncommon", 3).level).toBe(MAX_ITEM_LEVEL.uncommon); expect(generateRelic(99, "rare", 3).level).toBe(MAX_ITEM_LEVEL.rare); const common = generateItem(10, "common", 17, { allowedClasses: ["staff"] }); const promoted = levelUpItem(common, 18); expect(promoted.rarity).toBe("uncommon"); expect(promoted.level).toBe(1); expect(promoted.definitionId).toBe(common.definitionId); expect(promoted.affixes).toEqual(common.affixes); expect(promoted.skills).toEqual(common.skills); });
  test("rejects upgrading final-level Epic equipment without spending resources", () => { const state = progress(); const epic = generateItem(50, "epic", 19); state.inventoryTiles.push({ id: "max-epic", key: itemStackKey(epic), item: epic, quantity: 1 }); state.gold = 1_000_000; state.scraps.epic = 1_000; const result = upgradeFromInventory(state, "max-epic", () => "unused", () => 20); expect(result.changed).toBeFalse(); expect(state.gold).toBe(1_000_000); expect(state.scraps.epic).toBe(1_000); expect(state.inventoryTiles[0].quantity).toBe(1); });
});
describe("XP presentation", () => { test("retargets easing from the current displayed value", () => { const towardTwenty = lerpXpDisplay(0, 20); expect(towardTwenty).toBe(2); expect(lerpXpDisplay(towardTwenty, 50)).toBeCloseTo(6.8); }); });
describe("HUD preview values", () => { test("formats changed and removed values from currentVal and nullable newVal", () => { expect(formatPreviewValue({ currentVal: 10, newVal: 14 })).toBe("10 → 14"); expect(formatPreviewValue({ currentVal: 10, newVal: 10 })).toBe("10"); expect(formatPreviewValue({ currentVal: 10, newVal: null })).toBe("10 → —"); expect(previewTone({ currentVal: 10, newVal: 14 })).toBe("gain"); expect(previewTone({ currentVal: 10, newVal: 8 })).toBe("cost"); }); });
describe("spell range and recovery", () => { test("scales skill range and cooldown slightly with weapon level while natural healing stays weak", () => { expect(skillRange("bash", starterClub(), 4, 20)).toBe(145); expect(skillRange("bash", starterClub(), 100, 100)).toBe(405); const leveled = generateItem(10, "rare", 17, { allowedClasses: ["staff"] }); expect(skillRange("arcaneBolt", leveled, 1, 0)).toBeCloseTo(346.5); expect(skillCooldown("arcaneBolt", leveled)).toBeCloseTo(5 / 1.05); expect(derivedStats({ ...ZERO_STATS, spirit: 20 }).hpRegen).toBeCloseTo(0.105); }); });
describe("Healing scaling", () => { test("scales from level 1 to 100 and charges twice the restored HP", () => { expect(healingFraction(1)).toBeCloseTo(0.2); expect(healingFraction(100)).toBeCloseTo(0.9); expect(healingFraction(101)).toBeCloseTo(0.9); expect(healingCooldown(1)).toBeCloseTo(60); expect(healingCooldown(100)).toBeCloseTo(1); expect(healingCast(40, 100, 1)).toEqual({ restoredHp: 8, manaCost: 16 }); expect(healingCast(49, 50, 100)).toEqual({ restoredHp: 1, manaCost: 2 }); }); });
test("divides spell cooldown by Intelligence plus Agility with a safe floor", () => { expect(skillCooldown("fireBreath", starterClub(), { ...ZERO_STATS, intelligence: 2, agility: 3 })).toBeCloseTo(9 / 5); expect(skillCooldown("fireBreath", starterClub(), ZERO_STATS)).toBe(9); });
test("registers configurable Spirit relic perks", () => { expect(SKILLS.fireBreath).toMatchObject({ enemyEligible: true, cost: 4 }); expect(SKILLS.voodoo.passive).toBeTrue(); const perks = Array.from({ length: 100 }, (_, seed) => generateRelic(3, "rare", seed).skills); expect(perks.some((skills) => skills.includes("fireBreath"))).toBeTrue(); expect(perks.some((skills) => skills.includes("voodoo"))).toBeTrue(); });
test("connects WebSockets to the page origin unless server overrides it", () => { expect(gameSocketUrl({ host: "localhost:3000", protocol: "http:", search: "" } as Location)).toBe("ws://localhost:3000/ws"); expect(gameSocketUrl({ host: "game.test", protocol: "https:", search: "" } as Location)).toBe("wss://game.test/ws"); expect(gameSocketUrl({ host: "localhost:3000", protocol: "http:", search: "?server=pvp.railway%3A443" } as Location)).toBe("wss://pvp.railway/ws"); expect(gameSocketUrl({ host: "localhost:3000", protocol: "http:", search: "?ip=pvp.up.railway.app" } as Location)).toBe("wss://pvp.up.railway.app/ws"); expect(gameSocketUrl({ host: "localhost:3000", protocol: "http:", search: "?server=preferred.test&ip=legacy.test" } as Location)).toBe("wss://preferred.test/ws"); expect(gameSocketUrl({ host: "localhost:3000", protocol: "http:", search: "?server=ws%3A%2F%2F192.168.0.13%3A3000" } as Location)).toBe("ws://192.168.0.13:3000/ws"); expect(gameSocketUrl({ host: "localhost:3000", protocol: "http:", search: "?server=https%3A%2F%2Fpvp.railway%2Fgame" } as Location)).toBe("wss://pvp.railway/game/ws"); expect(gameSocketUrl({ host: "localhost:3000", protocol: "http:", search: "?server=ftp%3A%2F%2Fbad.test" } as Location)).toBe("ws://localhost:3000/ws"); });
