import { describe, expect, test } from "bun:test";
import { BALANCE_PROFILES } from "../common/balance";
import { bucklerBlockCost, rollWeaponDamage, skillRange, weaponAttackSpeed, weaponRange, weaponUsesProjectile } from "../common/combat";
import { collectIntoInventory, emptyScraps, equipFromInventory, extractFromInventory, inventoryCapacity, isEquippedTile, occupiedInventorySlots, purgeFromInventory, sellFromInventory, upgradeFromInventory } from "../common/inventory";
import { generateBuckler, generateItem, generateRelic, itemStackKey, levelUpItem, starterClub } from "../common/items";
import { cumulativeXpForLevel, DEFAULT_ALLOCATION, derivedStats, lerpXpDisplay, levelForXp, xpForNextLevel, ZERO_STATS } from "../common/progression";
import { parseClientMessage, type PlayerProgress } from "../common/protocol";
import { SeededRandom } from "../common/random";
import { regularCount, regularLevel, rivalLevel } from "../common/waves";
import { WEAPONS, SKILLS } from "../common/content";
import { effectiveSkillLevel } from "../src/game/systems/HeroCombatSystem";

function progress(): PlayerProgress { return { level: 0, xp: 0, stats: { ...ZERO_STATS }, allocation: { ...DEFAULT_ALLOCATION }, gold: 1000, souls: 0, scraps: emptyScraps(), mainHand: starterClub(), inventoryTiles: [], learnedSkills: ["healing"], learnedSkillLevels: { healing: 1 }, universalSkills: ["healing"] }; }
let id = 0;

describe("balance and waves", () => {
  test("keeps capped wave scaling", () => { const balance = BALANCE_PROFILES.normal; expect(regularCount(1, balance)).toBe(12); expect(regularLevel(3, 0, 16, balance)).toBe(1); expect(rivalLevel(5, 10, balance)).toBe(8); expect(regularCount(100, balance)).toBe(40); });
  test("development does not accelerate combat or rewards", () => { const item = starterClub(); const normal = rollWeaponDamage(item, ZERO_STATS, "hero", BALANCE_PROFILES.normal, new SeededRandom(2)); expect(rollWeaponDamage(item, ZERO_STATS, "hero", BALANCE_PROFILES.dev, new SeededRandom(2))).toBeCloseTo(normal); expect(BALANCE_PROFILES.dev.rewards).toEqual(BALANCE_PROFILES.normal.rewards); });
});
describe("attack timing", () => { test("uses damped weight handling for physical and magic weapons", () => { const club = starterClub(); expect(weaponAttackSpeed(club, ZERO_STATS)).toBeCloseTo(10 / 12); expect(weaponAttackSpeed(club, { ...ZERO_STATS, agility: 100 })).toBeCloseTo(20 / 12); const generatedStaff = generateItem(0, "common", 5, { allowedClasses: ["staff"] }); const staff = { ...generatedStaff, modifiers: { ...generatedStaff.modifiers, attackSpeedMultiplier: 1 } }; expect(weaponAttackSpeed(staff, { ...ZERO_STATS, strength: 100, spirit: 100 })).toBeCloseTo(20 / 16); expect(weaponAttackSpeed(staff, { ...ZERO_STATS, agility: 1_000 })).toBeCloseTo(10 / 16); }); });
describe("XP curve", () => { test("uses cached Fibonacci-like level costs", () => { expect([0, 1, 2, 3, 4, 5].map(xpForNextLevel)).toEqual([100, 150, 250, 400, 650, 1050]); expect(cumulativeXpForLevel(4)).toBe(900); expect(levelForXp(899)).toBe(3); expect(levelForXp(900)).toBe(4); }); });

describe("permanent inventory", () => {
  test("toggles an equipped offhand back to unequipped", () => { const state = progress(); const buckler = { ...generateBuckler(0, "common", 12), requirements: {} }; collectIntoInventory(state, buckler, () => `tile-${++id}`, () => ++id); const tile = state.inventoryTiles[0]; expect(equipFromInventory(state, tile.id).changed).toBeTrue(); expect(state.offHand).toBeDefined(); expect(equipFromInventory(state, tile.id).changed).toBeTrue(); expect(state.offHand).toBeUndefined(); expect(tile.quantity).toBe(1); });
  test("prices percentage return above one stamina and upgrades it toward one", () => { const base = { ...generateBuckler(0, "rare", 18), reflectionComponents: ["return" as const] }; const stats = { ...ZERO_STATS, agility: 50 }; const baseCost = bucklerBlockCost(base, stats); const upgraded = levelUpItem(base, 19); expect(baseCost).toBeGreaterThan(1); expect(bucklerBlockCost(upgraded, stats)).toBeGreaterThan(1); expect(bucklerBlockCost(upgraded, stats)).toBeLessThan(baseCost); });
  test("equips relics as offhands and preserves their attraction passive", () => { const state = progress(); const relic = { ...generateRelic(0, "rare", 12), attractionSpeed: 35 }; collectIntoInventory(state, relic, () => `tile-${++id}`, () => ++id); expect(equipFromInventory(state, state.inventoryTiles[0].id).changed).toBeTrue(); expect(state.offHand?.itemKind).toBe("relic"); expect(state.offHand?.attractionSpeed).toBe(35); });
  test("removes empty stacks and releases their capacity immediately", () => { const state = progress(); expect(inventoryCapacity(0)).toBe(4); for (let n = 0; n < 4; n += 1) expect(collectIntoInventory(state, generateItem(n, "common", 100 + n), () => `tile-${++id}`, () => ++id).changed).toBeTrue(); const tile = state.inventoryTiles[0]; purgeFromInventory(state, tile.id); expect(state.inventoryTiles.some((candidate) => candidate.id === tile.id)).toBeFalse(); expect(occupiedInventorySlots(state)).toBe(3); expect(collectIntoInventory(state, generateItem(9, "epic", 999), () => `tile-${++id}`, () => ++id).changed).toBeTrue(); expect(occupiedInventorySlots(state)).toBe(4); });
  test("upgrades one source copy without creating persistent automation", () => { const state = progress(); const item = generateItem(1, "common", 41); collectIntoInventory(state, item, () => `tile-${++id}`, () => ++id); collectIntoInventory(state, { ...item, id: "copy" }, () => `tile-${++id}`, () => ++id); state.scraps.common = 10; const gold = state.gold; const result = upgradeFromInventory(state, state.inventoryTiles[0].id, () => `tile-${++id}`, () => 55); expect(result.changed).toBeTrue(); expect(result.created?.level).toBe(2); expect(state.inventoryTiles[0].quantity).toBe(1); expect(state.inventoryTiles[1].quantity).toBe(1); expect(state.scraps.common).toBe(4); expect(state.gold).toBeLessThan(gold); });
  test("upgrades a lone equipped copy in place when resources are sufficient", () => { const state = progress(); const item = { ...generateItem(1, "common", 141), requirements: {} }; collectIntoInventory(state, item, () => `tile-${++id}`, () => ++id); const tile = state.inventoryTiles.find((candidate) => candidate.key === itemStackKey(item))!; expect(equipFromInventory(state, tile.id).changed).toBeTrue(); state.scraps.common = 20; const result = upgradeFromInventory(state, tile.id, () => `tile-${++id}`, () => 155); expect(result.changed).toBeTrue(); expect(state.mainHand.level).toBe(2); const upgraded = state.inventoryTiles.find((candidate) => candidate.key === itemStackKey(state.mainHand)); expect(upgraded?.quantity).toBe(1); expect(isEquippedTile(state, upgraded!)).toBeTrue(); expect(state.inventoryTiles.some((candidate) => candidate.id === tile.id)).toBeFalse(); });
  test("retains equipped copies and rejects destructive actions", () => { const state = progress(); const item = { ...generateItem(1, "rare", 71), requirements: {} }; collectIntoInventory(state, item, () => `tile-${++id}`, () => ++id); const tile = state.inventoryTiles[0]; expect(equipFromInventory(state, tile.id).changed).toBeTrue(); expect(tile.quantity).toBe(1); expect(isEquippedTile(state, tile)).toBeTrue(); expect(state.inventoryTiles.some((candidate) => candidate.key === itemStackKey(starterClub()))).toBeTrue(); const gold = state.gold; const scraps = state.scraps.rare; expect(sellFromInventory(state, tile.id).changed).toBeFalse(); expect(purgeFromInventory(state, tile.id).changed).toBeFalse(); expect(tile.quantity).toBe(1); expect(state.gold).toBe(gold); expect(state.scraps.rare).toBe(scraps); });
});

describe("protocol validation", () => { test("accepts v14 bulk and respec commands and rejects retired automation", () => { expect(parseClientMessage({ type: "upgradeItem", tileId: "tile-1", bulk: true })).toEqual({ type: "upgradeItem", tileId: "tile-1", bulk: true }); expect(parseClientMessage({ type: "respecStats", allocation: { agility: 1, strength: 1, magic: 1, spirit: 1, intelligence: 1 } })?.type).toBe("respecStats"); expect(parseClientMessage({ type: "setStackAutomation", tileId: "tile-1", mode: "sell", maxRarity: "rare" })).toBeUndefined(); expect(parseClientMessage({ type: "mergeItem", tileId: "tile-1" })).toBeUndefined(); expect(parseClientMessage({ type: "creepKilled", unitId: "unit-1", xpReward: 9999 })).toBeUndefined(); expect(parseClientMessage({ type: "updateAllocation", allocation: { agility: 5 } })).toBeUndefined(); }); });
describe("weapon skills", () => { test("gives every weapon class a distinct registered signature skill", () => { const skills = Object.values(WEAPONS).map((weapon) => weapon.skill); expect(new Set(skills).size).toBe(Object.keys(WEAPONS).length); for (const skill of skills) expect(skill && SKILLS[skill]).toBeDefined(); expect(WEAPONS.mace.skill).toBe("shockwave"); expect(WEAPONS.axe.skill).toBe("cleave"); expect(WEAPONS.hammer.skill).toBe("orbitingHammers"); expect(SKILLS.orbitingHammers.resource).toBe("mana"); }); });
describe("equipped skill levels", () => { test("temporarily adds one level and requires matching gear until universally unlocked", () => { const state = progress(); expect(effectiveSkillLevel(state, "bash")).toBe(1); state.learnedSkills.push("bash"); state.learnedSkillLevels.bash = 3; expect(effectiveSkillLevel(state, "bash")).toBe(4); state.mainHand = { ...state.mainHand, skills: [] }; expect(effectiveSkillLevel(state, "bash")).toBe(0); state.universalSkills.push("bash"); expect(effectiveSkillLevel(state, "bash")).toBe(3); const relic = generateRelic(1, "rare", 0); state.offHand = relic; expect(relic.skills).toContain("gravityPull"); expect(effectiveSkillLevel(state, "gravityPull")).toBe(1); }); });
describe("Epic skill extraction", () => { test("unlocks extracted skills for every weapon only at Epic rarity", () => { const rareState = progress(); const rare = generateItem(1, "rare", 17, { allowedClasses: ["staff"] }); rareState.inventoryTiles.push({ id: "rare", key: itemStackKey(rare), item: rare, quantity: 1 }); rareState.gold = 10_000; expect(extractFromInventory(rareState, "rare").changed).toBeTrue(); expect(rareState.learnedSkills).toContain("arcaneBolt"); expect(rareState.universalSkills).not.toContain("arcaneBolt"); const epicState = progress(); const epic = generateItem(1, "epic", 27, { allowedClasses: ["staff"] }); epicState.inventoryTiles.push({ id: "epic", key: itemStackKey(epic), item: epic, quantity: 1 }); epicState.gold = 10_000; expect(extractFromInventory(epicState, "epic").changed).toBeTrue(); expect(epicState.universalSkills).toEqual(expect.arrayContaining(["arcaneBolt", "frostOrb"])); }); });
describe("spell resources", () => { test("registers Rent as life and buckler blocking as stamina", () => { expect(SKILLS.rent.resource).toBe("life"); expect(SKILLS.blocking.resource).toBe("stamina"); expect(generateBuckler(0, "common", 12).skills).toEqual(["blocking"]); }); });
describe("extractable offhand and staff skills", () => {
  test("adds Gravity Pull to attracting relics and high-rarity skills to spiked bucklers and staves", () => {
    const relic = Array.from({ length: 50 }, (_, seed) => generateRelic(1, "rare", seed)).find((item) => item.attractionSpeed > 0)!;
    const buckler = Array.from({ length: 100 }, (_, seed) => generateBuckler(1, "rare", seed)).find((item) => item.reflectionComponents.length > 0)!;
    const staff = generateItem(1, "rare", 17, { allowedClasses: ["staff"] });
    expect(relic.skills).toContain("gravityPull"); expect(buckler.skills).toEqual(expect.arrayContaining(["blocking", "thorns", "reflectiveSurge"])); expect(staff.skills).toEqual(expect.arrayContaining(["arcaneBolt", "frostOrb"]));
    expect(SKILLS.gravityPull.cooldown).toBe(18); expect(SKILLS.frostOrb.cooldown).toBe(20);
  });
});
describe("throwing axes", () => { test("generates a one-handed short-ranged projectile weapon with inherent bleed", () => { const axe = generateItem(0, "common", 17, { allowedClasses: ["throwingAxe"] }); expect(axe.hands).toBe(1); expect(axe.skills).toEqual(["rendingThrow"]); expect(axe.modifiers.bleedChance).toBeGreaterThanOrEqual(0.15); expect(weaponRange(axe)).toBe(210); expect(weaponUsesProjectile(axe)).toBeTrue(); }); });
describe("item sustain", () => { test("preserves rolled sustain passives through upgrades", () => { const vampiric = generateItem(2, "rare", 8); expect(vampiric.modifiers.lifeStealBase).toBe(0.02); const upgraded = levelUpItem(vampiric, 2); expect(upgraded.modifiers.lifeStealBase).toBe(0.02); expect(upgraded.modifiers.strengthRegenMultiplier).toBe(0); }); });
describe("XP presentation", () => { test("retargets easing from the current displayed value", () => { const towardTwenty = lerpXpDisplay(0, 20); expect(towardTwenty).toBe(2); expect(lerpXpDisplay(towardTwenty, 50)).toBeCloseTo(6.8); }); });
describe("spell range and recovery", () => { test("scales skill range with level and Spirit while natural healing stays weak", () => { expect(skillRange("bash", starterClub(), 4, 20)).toBe(145); expect(skillRange("bash", starterClub(), 100, 100)).toBe(405); expect(derivedStats({ ...ZERO_STATS, spirit: 20 }).hpRegen).toBeCloseTo(0.105); }); });
