import { describe, expect, test } from "bun:test";
import { BALANCE_PROFILES } from "../common/balance";
import { emptyScraps } from "../common/inventory";
import { generateItem, itemStackKey } from "../common/items";
import { cumulativeXpForLevel } from "../common/progression";
import type { PlayerId, ServerMessage } from "../common/protocol";
import type { RandomSource } from "../common/random";
import { InMemoryPlayerRepository } from "../server/domain";
import { GameService } from "../server/GameService";

class FixedRandom implements RandomSource { constructor(private readonly value = 0) { } next(): number { return this.value; } }
class SequenceRandom implements RandomSource { private values: number[] = []; set(...values: number[]): void { this.values = values; } next(): number { return this.values.shift() ?? 0.5; } }
function harness(random: RandomSource = new FixedRandom(0)) { const messages = new Map<PlayerId, ServerMessage[]>(); const repository = new InMemoryPlayerRepository(); let nextId = 0; const game = new GameService({ repository, balance: BALANCE_PROFILES.dev, random, createId: () => `id-${++nextId}`, send: (id, message) => messages.set(id, [...(messages.get(id) ?? []), structuredClone(message)]) }); return { game, repository, messages }; }
function enterPair(game: GameService, one: ReturnType<GameService["join"]>, two: ReturnType<GameService["join"]>): void { game.handle(one.id, { type: "enterRealm" }); game.handle(two.id, { type: "enterRealm" }); }

describe("realm game service", () => {
  test("starts new players with a throwing axe and buckler", () => {
    const { game } = harness(); const player = game.join("Starter");
    expect(player.progress.mainHand.definitionId).toBe("throwingAxe");
    expect(player.progress.offHand?.definitionId).toBe("buckler");
    expect(player.progress.inventoryTiles.map((tile) => tile.item.definitionId)).toEqual(["throwingAxe", "buckler"]);
    expect(player.progress.inventoryTiles.every((tile) => tile.quantity === 1)).toBeTrue();
  });
  test("logs player connection lifecycle with stable identity", () => {
    const repository = new InMemoryPlayerRepository(); const events: Array<{ event: "connected" | "disconnected"; id: string; name: string }> = []; let nextId = 0;
    const game = new GameService({ repository, balance: BALANCE_PROFILES.dev, random: new FixedRandom(), createId: () => `id-${++nextId}`, send: () => { }, logPlayerLifecycle: (event, player) => events.push({ event, id: player.id, name: player.name }) });
    const player = game.join(" Logger "); game.disconnect(player.id);
    expect(events).toEqual([{ event: "connected", id: player.id, name: "Logger" }, { event: "disconnected", id: player.id, name: "Logger" }]);
  });
  test("logs realm entry and exit for each matched player", () => {
    const repository = new InMemoryPlayerRepository(); const events: Array<{ event: "entered" | "left"; playerId: string; realmId: string; opponentIds: string[] }> = []; let nextId = 0;
    const game = new GameService({ repository, balance: BALANCE_PROFILES.dev, random: new FixedRandom(), createId: () => `id-${++nextId}`, send: () => { }, logRealmLifecycle: (event, playerId, realmId, opponentIds) => events.push({ event, playerId, realmId, opponentIds }) });
    const one = game.join("One"); const two = game.join("Two"); enterPair(game, one, two); const realmId = one.realmId!;
    game.disconnect(one.id);
    expect(events).toEqual([
      { event: "entered", playerId: one.id, realmId, opponentIds: [two.id] },
      { event: "entered", playerId: two.id, realmId, opponentIds: [one.id] },
      { event: "left", playerId: one.id, realmId, opponentIds: [two.id] },
      { event: "left", playerId: two.id, realmId, opponentIds: [one.id] },
    ]);
  });
  test("starts in the lobby and activates a stable 1v1 after opting in", () => { const { game, messages } = harness(); const one = game.join("One"); expect(one.realmOptedIn).toBeFalse(); expect(messages.get(one.id)?.find((m) => m.type === "incomingWave")?.wave.mode).toBe("training"); const two = game.join("Two"); expect(one.realmId).toBeUndefined(); enterPair(game, one, two); expect(one.realmId).toBe(two.realmId); expect(one.issuedUnits.size).toBe(13); expect([...one.issuedUnits.values()][0].mode).toBe("competitive"); });
  test("starts a half-XP solo game when no opponent is available", () => { const { game, messages } = harness(); const player = game.join("Solo"); game.handle(player.id, { type: "enterRealm" }); const wave = messages.get(player.id)?.filter((message) => message.type === "incomingWave").at(-1); expect(wave?.type === "incomingWave" ? wave.wave.mode : undefined).toBe("solo"); const unitId = [...player.issuedUnits.entries()].find(([, issued]) => !issued.build.isRival)?.[0]; expect(unitId).toBeDefined(); game.handle(player.id, { type: "creepDefeated", unitId: unitId! }); expect(player.progress.xp).toBe(5); expect(player.score).toBe(2); });
  test("shows the lobby player as their own neighbor and sends to a future training carrier", () => { const { game, messages } = harness(); const player = game.join("Mirror"); const welcome = messages.get(player.id)?.find((message) => message.type === "welcome"); expect(welcome?.type === "welcome" ? welcome.realm.guards[0]?.id : undefined).toBe(player.id); expect(welcome?.type === "welcome" ? welcome.realm.attackers[0]?.id : undefined).toBe(player.id); const item = generateItem(2, "rare", 75); player.progress.inventoryTiles.push({ id: "mirror-tile", key: itemStackKey(item), item, quantity: 1 }); game.handle(player.id, { type: "sendItem", tileId: "mirror-tile" }); expect(player.incomingQueues.get(player.id)).toHaveLength(1); game.dispatchWaves(); expect(player.incomingQueues.get(player.id)).toBeUndefined(); const carrier = [...player.issuedUnits.values()].find((issued) => issued.build.emitterId === player.id); expect(carrier?.mode).toBe("training"); expect(carrier?.build.mainHand.definitionId).toBe(item.definitionId); });
  test("resolves competitive units once and keeps Gold drops server-owned until collection", () => { const { game, messages } = harness(); const one = game.join("One"); const two = game.join("Two"); enterPair(game, one, two); const unitId = one.issuedUnits.keys().next().value as string; game.handle(one.id, { type: "creepDefeated", unitId }); expect(one.score).toBe(2); expect(one.progress.xp).toBe(10); expect(one.groundDrops.size).toBe(1); const drop = [...one.groundDrops.values()][0]; expect(drop.kind).toBe("gold"); const gold = one.progress.gold; game.handle(one.id, { type: "creepDefeated", unitId }); expect(one.score).toBe(2); expect(messages.get(one.id)?.some((m) => m.type === "serverNotice")).toBeTrue(); game.handle(one.id, { type: "collectDrop", dropId: drop.id }); expect(one.progress.gold).toBe(gold + (drop.kind === "gold" ? drop.amount : 0)); expect(one.groundDrops.size).toBe(0); });
  test("collects typed Scrap drops exactly once", () => { const { game } = harness(); const player = game.join("Scrapper"); player.groundDrops.set("scrap-drop", { id: "scrap-drop", kind: "scrap", rarity: "rare", amount: 3 }); game.handle(player.id, { type: "collectDrop", dropId: "scrap-drop" }); expect(player.progress.scraps.rare).toBe(3); game.handle(player.id, { type: "collectDrop", dropId: "scrap-drop" }); expect(player.progress.scraps.rare).toBe(3); });
  test("defers pushed equipment and returns it to the same player next wave", () => { const { game } = harness(); const player = game.join("Boomerang"); const item = generateItem(2, "rare", 92); player.groundDrops.set("outbound", { id: "outbound", kind: "item", item }); game.handle(player.id, { type: "deferDrop", dropId: "outbound" }); expect(player.groundDrops.has("outbound")).toBeFalse(); expect(player.deferredItems).toHaveLength(1); game.dispatchWaves(); expect(player.deferredItems).toHaveLength(0); expect(player.progress.inventoryTiles.some((tile) => tile.key === itemStackKey(item))).toBeTrue(); });
  test("converts a successful equipment roll into a typed Scrap drop", () => { const random = new SequenceRandom(); const { game } = harness(random); const one = game.join("One"); const two = game.join("Two"); enterPair(game, one, two); const [unitId, issued] = [...one.issuedUnits.entries()].find(([, value]) => !value.build.isRival)!; random.set(0.3, 0, 0.5, 0); game.handle(one.id, { type: "creepDefeated", unitId }); const drop = [...one.groundDrops.values()][0]; expect(drop.kind).toBe("scrap"); if (drop.kind === "scrap") { expect(drop.rarity).toBe(issued.build.mainHand.rarity); expect(drop.amount).toBe(Math.max(1, Math.ceil(issued.build.mainHand.level / 3))); } });
  test("sends equipment into a future carrier and retains attribution", () => { const { game } = harness(); const sender = game.join("Sender"); const target = game.join("Target"); enterPair(game, sender, target); const item = generateItem(2, "rare", 77); sender.progress.inventoryTiles.push({ id: "tile", key: itemStackKey(item), item, quantity: 2 }); game.handle(sender.id, { type: "sendItem", tileId: "tile" }); expect(target.incomingQueues.get(sender.id)).toHaveLength(1); game.dispatchWaves(); const carrier = [...target.issuedUnits.values()].find((issued) => issued.build.emitterId === sender.id); expect(carrier?.build.mainHand.definitionId).toBe(item.definitionId); expect(sender.progress.inventoryTiles[0].quantity).toBe(1); });
  test("shift bulk sends every available copy", () => { const { game } = harness(); const sender = game.join("Sender"); const target = game.join("Target"); enterPair(game, sender, target); const item = generateItem(2, "rare", 79); sender.progress.inventoryTiles.push({ id: "bulk-tile", key: itemStackKey(item), item, quantity: 3 }); game.handle(sender.id, { type: "sendItem", tileId: "bulk-tile", bulk: true }); expect(target.incomingQueues.get(sender.id)).toHaveLength(3); expect(sender.progress.inventoryTiles.some((tile) => tile.id === "bulk-tile")).toBeFalse(); });
  test("shift bulk sell and purge multiply rewards across the whole stack", () => { const { game } = harness(); const player = game.join("Merchant"); const sold = generateItem(2, "rare", 83); player.progress.inventoryTiles.push({ id: "sell-stack", key: itemStackKey(sold), item: sold, quantity: 3 }); const gold = player.progress.gold; game.handle(player.id, { type: "sellItem", tileId: "sell-stack", bulk: true }); expect(player.progress.gold).toBe(gold + 3 * sold.sellValue); expect(player.progress.inventoryTiles.some((tile) => tile.id === "sell-stack")).toBeFalse(); const purged = generateItem(4, "uncommon", 85); player.progress.inventoryTiles.push({ id: "purge-stack", key: itemStackKey(purged), item: purged, quantity: 3 }); const scraps = player.progress.scraps.uncommon; game.handle(player.id, { type: "purgeItem", tileId: "purge-stack", bulk: true }); expect(player.progress.scraps.uncommon).toBe(scraps + 3 * Math.max(1, Math.ceil(purged.level / 3))); expect(player.progress.inventoryTiles.some((tile) => tile.id === "purge-stack")).toBeFalse(); });
  test("shift bulk upgrades the clicked stack while resources permit", () => { const { game } = harness(); const player = game.join("Smith"); const item = generateItem(1, "common", 81); player.progress.inventoryTiles.push({ id: "upgrade-tile", key: itemStackKey(item), item, quantity: 3 }); player.progress.gold = 10_000; player.progress.scraps.common = 100; game.handle(player.id, { type: "upgradeItem", tileId: "upgrade-tile", bulk: true }); const upgraded = player.progress.inventoryTiles.find((tile) => tile.item.level === 2); expect(upgraded?.quantity).toBe(3); expect(player.progress.inventoryTiles.some((tile) => tile.id === "upgrade-tile")).toBeFalse(); expect(player.progress.scraps.common).toBe(88); });
  test("charges level times 100 to reapply a stat ratio retroactively", () => { const { game, messages } = harness(); const player = game.join("Planner"); player.progress.level = 4; player.progress.gold = 500; player.progress.stats = { agility: 9, strength: 8, magic: 7, spirit: 6, intelligence: 5 }; const allocation = { agility: 2, strength: 1, magic: 1, spirit: 1, intelligence: 0 }; game.handle(player.id, { type: "respecStats", allocation }); expect(player.progress.gold).toBe(100); expect(player.progress.allocation).toEqual(allocation); expect(player.progress.stats).toEqual({ agility: 8, strength: 4, magic: 4, spirit: 4, intelligence: 0 }); const before = structuredClone(player.progress); game.handle(player.id, { type: "respecStats", allocation }); expect(player.progress).toEqual(before); expect(messages.get(player.id)?.at(-1)?.type).toBe("serverNotice"); });
  test("credits the final sent-carrier realm defeat and rematches it", () => { const { game } = harness(); const killer = game.join("Killer"); const victim = game.join("Victim"); enterPair(game, killer, victim); const oldRealm = victim.realmId; killer.progress.level = 5; killer.progress.xp = cumulativeXpForLevel(5); victim.progress.level = 5; const item = generateItem(2, "rare", 88); killer.progress.inventoryTiles.push({ id: "tile", key: itemStackKey(item), item, quantity: 1 }); game.handle(killer.id, { type: "sendItem", tileId: "tile" }); game.dispatchWaves(); const source = [...victim.issuedUnits.values()].find((issued) => issued.build.emitterId === killer.id)!.build.id; game.handle(victim.id, { type: "heroDefeated", sourceUnitId: source }); expect(killer.progress.xp).toBe(cumulativeXpForLevel(5) + 500); expect(killer.progress.level).toBe(5); expect(killer.progress.souls).toBe(1); expect(victim.realmId).not.toBe(oldRealm); });
  test("training kills grant nothing", () => { const { game } = harness(); const player = game.join("Trainee"); const unitId = player.issuedUnits.keys().next().value as string; game.handle(player.id, { type: "creepDefeated", unitId }); expect(player.score).toBe(0); expect(player.progress.xp).toBe(0); expect(player.progress.scraps).toEqual(emptyScraps()); });
  test("authors rare enemy bonus skills in serialized regular builds", () => { const { game } = harness(new FixedRandom(0)); const player = game.join("Skilled"); const regulars = [...player.issuedUnits.values()].filter(({ build }) => !build.isRival); expect(regulars.length).toBeGreaterThan(0); expect(regulars.every(({ build }) => build.bonusSkills?.includes("fireBreath"))).toBeTrue(); });
});
