import { describe, expect, test } from "bun:test";
import { BALANCE_PROFILES } from "../common/balance";
import { emptyScraps } from "../common/inventory";
import { generateItem, itemStackKey } from "../common/items";
import { cumulativeXpForLevel } from "../common/progression";
import type { PlayerId, ServerMessage } from "../common/protocol";
import type { RandomSource } from "../common/random";
import { InMemoryPlayerRepository } from "../server/domain";
import { GameService } from "../server/GameService";

class FixedRandom implements RandomSource { constructor(private readonly value = 0) {} next(): number { return this.value; } }
function harness() { const messages = new Map<PlayerId, ServerMessage[]>(); const repository = new InMemoryPlayerRepository(); let nextId = 0; const game = new GameService({ repository, balance: BALANCE_PROFILES.dev, random: new FixedRandom(0), createId: () => `id-${++nextId}`, send: (id, message) => messages.set(id, [...(messages.get(id) ?? []), structuredClone(message)]) }); return { game, repository, messages }; }
function enterPair(game: GameService, one: ReturnType<GameService["join"]>, two: ReturnType<GameService["join"]>): void { game.handle(one.id, { type: "enterRealm" }); game.handle(two.id, { type: "enterRealm" }); }

describe("realm game service", () => {
  test("starts in the lobby and activates a stable 1v1 after opting in", () => { const { game, messages } = harness(); const one = game.join("One"); expect(one.realmOptedIn).toBeFalse(); expect(messages.get(one.id)?.find((m) => m.type === "incomingWave")?.wave.mode).toBe("training"); const two = game.join("Two"); expect(one.realmId).toBeUndefined(); enterPair(game, one, two); expect(one.realmId).toBe(two.realmId); expect(one.issuedUnits.size).toBe(13); expect([...one.issuedUnits.values()][0].mode).toBe("competitive"); });
  test("starts a half-XP solo game when no opponent is available", () => { const { game, messages } = harness(); const player = game.join("Solo"); game.handle(player.id, { type: "enterRealm" }); const wave = messages.get(player.id)?.filter((message) => message.type === "incomingWave").at(-1); expect(wave?.type === "incomingWave" ? wave.wave.mode : undefined).toBe("solo"); const unitId = [...player.issuedUnits.entries()].find(([, issued]) => !issued.build.isRival)?.[0]; expect(unitId).toBeDefined(); game.handle(player.id, { type: "creepDefeated", unitId: unitId! }); expect(player.progress.xp).toBe(5); expect(player.score).toBe(2); });
  test("resolves competitive units once and keeps drops server-owned", () => { const { game, messages } = harness(); const one = game.join("One"); const two = game.join("Two"); enterPair(game, one, two); const unitId = one.issuedUnits.keys().next().value as string; game.handle(one.id, { type: "creepDefeated", unitId }); expect(one.score).toBe(2); expect(one.progress.xp).toBe(10); expect(one.groundDrops.size).toBe(1); game.handle(one.id, { type: "creepDefeated", unitId }); expect(one.score).toBe(2); expect(messages.get(one.id)?.some((m) => m.type === "serverNotice")).toBeTrue(); const dropId = one.groundDrops.keys().next().value as string; game.handle(one.id, { type: "collectDrop", dropId }); expect(one.progress.inventoryTiles.some((tile) => tile.item.id.includes("drop") && tile.quantity === 1)).toBeTrue(); });
  test("sends equipment into a future carrier and retains attribution", () => { const { game } = harness(); const sender = game.join("Sender"); const target = game.join("Target"); enterPair(game, sender, target); const item = generateItem(2, "rare", 77); sender.progress.inventoryTiles.push({ id: "tile", key: itemStackKey(item), item, quantity: 2, automation: "keep" }); game.handle(sender.id, { type: "sendItem", tileId: "tile" }); expect(target.incomingQueues.get(sender.id)).toHaveLength(1); game.dispatchWaves(); const carrier = [...target.issuedUnits.values()].find((issued) => issued.build.emitterId === sender.id); expect(carrier?.build.mainHand.definitionId).toBe(item.definitionId); expect(sender.progress.inventoryTiles[0].quantity).toBe(1); });
  test("credits the final sent-carrier realm defeat and rematches it", () => { const { game } = harness(); const killer = game.join("Killer"); const victim = game.join("Victim"); enterPair(game, killer, victim); const oldRealm = victim.realmId; killer.progress.level = 5; killer.progress.xp = cumulativeXpForLevel(5); victim.progress.level = 5; const item = generateItem(2, "rare", 88); killer.progress.inventoryTiles.push({ id: "tile", key: itemStackKey(item), item, quantity: 1, automation: "keep" }); game.handle(killer.id, { type: "sendItem", tileId: "tile" }); game.dispatchWaves(); const source = [...victim.issuedUnits.values()].find((issued) => issued.build.emitterId === killer.id)!.build.id; game.handle(victim.id, { type: "heroDefeated", sourceUnitId: source }); expect(killer.progress.level).toBe(6); expect(killer.progress.souls).toBe(1); expect(victim.realmId).not.toBe(oldRealm); });
  test("training kills grant nothing", () => { const { game } = harness(); const player = game.join("Trainee"); const unitId = player.issuedUnits.keys().next().value as string; game.handle(player.id, { type: "creepDefeated", unitId }); expect(player.score).toBe(0); expect(player.progress.xp).toBe(0); expect(player.progress.scraps).toEqual(emptyScraps()); });
});
