/** @jsx h */
import { equippedPerks, itemRequirementMultiplier, itemStackKey, starterClub, statsWithItemBonuses, type ItemInstance, type SkillId } from "../../common/items";
import { STAT_KEYS, cumulativeXpForLevel, integerAllocation, lerpXpDisplay, levelForXp, xpForNextLevel, type Stats } from "../../common/progression";
import type { HeroSummary, PlayerProgress, PublicHeroProfile, RealmState, UnitBuild } from "../../common/protocol";
import type { PlayerState } from "../game/types";
import { h } from "./dom";
import { itemTile, orderInventoryTiles } from "./InventoryView";
import { occupiedInventorySlots } from "../../common/inventory";
import { bindRequirementPreview, itemDetails } from "./ItemDetails";
import type { CurrencyPreview, HudCallbacks, SpellSlot } from "./types";
import { bucklerBlockChance, bucklerBlockCost, cappedSkillLevel, cooldownScale, healingCooldown, skillCooldown, skillRange, spellPower, weaponAttackSpeed, weaponDamage, weaponRange } from "../../common/combat";
import { derivedStats } from "../../common/progression";
import { SKILLS } from "../../common/content";
import { effectiveSkillLevel } from "../game/systems/HeroCombatSystem";
import { applyPreviewClass, formatPreviewValue, previewTone, type PreviewValue } from "./preview";
export type { HudCallbacks, SpellSlot } from "./types";
declare global { namespace JSX { interface IntrinsicElements { [elementName: string]: Record<string, unknown> } } }

export class Hud {
  private player?: PlayerState; private inspected?: UnitBuild; private inspectedXp?: number; private realm?: RealmState;
  private readonly joinPanel: HTMLElement; private readonly gameHud: HTMLElement; private readonly nameInput: HTMLInputElement;
  private readonly leaderboardNode = <div class="leaderboard" /> as HTMLElement; private readonly publicSheet = <aside class="character-panel public-character-panel is-hidden" /> as HTMLElement;
  private readonly characterPanel: HTMLElement; private readonly inventoryPanel: HTMLElement; private readonly characterToggle: HTMLButtonElement; private readonly inventoryToggle: HTMLButtonElement;
  private panelTriggers = { character: false, inventory: false };
  private readonly realmPanel = <div class="realm-panel" /> as HTMLElement;
  private readonly noticeNode = <div class="notice" role="status" aria-live="polite">Enter a name to join.</div> as HTMLElement;
  private readonly joinNoticeNode = <div class="notice" role="status" aria-live="polite">Enter a name to join.</div> as HTMLElement; private readonly sheetNode = <div class="sheet-content" /> as HTMLElement;
  private readonly inventoryNode = <div class="inventory-content" /> as HTMLElement; private readonly allocationNode = <form class="allocation-panel" /> as HTMLElement;
  private readonly inventoryCount = <strong /> as HTMLElement;
  private readonly inventoryHeader = <div class="inventory-header"><div class="currency-grid">{currencyCell("Gold", 0, "gold")}{currencyCell("Souls", 0, "souls")}{currencyCell("Common", 0, "common")}{currencyCell("Uncommon", 0, "uncommon")}{currencyCell("Rare", 0, "rare")}{currencyCell("Epic", 0, "epic")}</div>{this.inventoryCount}</div> as HTMLElement;
  private readonly backpackScroll = <div class="backpack-scroll" /> as HTMLElement;
  private readonly spellBar = <section class="spell-bar" /> as HTMLElement; private readonly resourceDock = <section class="resource-dock" /> as HTMLElement;
  private readonly healthBar = resourceBar("Health", "health"); private readonly manaBar = resourceBar("Mana", "mana");
  private readonly staminaLine = <div class="stamina-line" role="progressbar" aria-label="Stamina" aria-valuemin="0"><span /></div> as HTMLElement;
  private readonly xpName = <small /> as HTMLElement; private readonly xpLevel = <strong /> as HTMLElement;
  private readonly xpBadge = <div class="xp-badge" role="progressbar" aria-label="Experience" aria-valuemin="0"><div>{this.xpName}{this.xpLevel}</div></div> as HTMLElement;
  private readonly waveBanner = <div class="wave-banner" aria-live="polite"><strong /><span /></div> as HTMLElement;
  private readonly centerToast = <div class="center-toast" role="status" aria-live="polite" /> as HTMLElement;
  private readonly xpToast = <div class="xp-toast" role="status" aria-live="polite" /> as HTMLElement;
  private waveTimer?: number; private centerToastTimer?: number; private xpToastTimer?: number;
  private displayedXp?: number; private targetXp = 0;
  private staticSignature = ""; private dynamicSignature = ""; private realmSignature = ""; private spellStructureSignature = ""; private allocationSignature = ""; private lastWaveNumber?: number;
  private staticProgress?: PlayerProgress; private staticPlayerName = ""; private staticReceivesDeathEchoes = false; private activeMainHand?: HTMLElement;
  private currentSpells: SpellSlot[] = []; private spellPreview?: Map<SkillId, number | null>;
  private readonly spellNodes = new Map<string, HTMLElement>();
  constructor(private readonly root: HTMLDivElement, private readonly callbacks: HudCallbacks) {
    this.nameInput = <input name="name" maxlength="20" placeholder="Player name" autocomplete="off" /> as HTMLInputElement;
    const joinForm = <form>{this.nameInput}<button type="submit">Join</button></form> as HTMLElement;
    this.joinPanel = <section class="join-panel">{joinForm}{this.joinNoticeNode}<h2>Heroes</h2>{this.leaderboardNode}</section> as HTMLElement;
    joinForm.onsubmit = (event) => { event.preventDefault(); const name = this.nameInput.value.trim(); if (name) callbacks.onJoin(name); };
    const back = <button class="inspect-back is-hidden" type="button">Back to hero</button> as HTMLButtonElement; back.onclick = callbacks.onBack;
    this.characterToggle = <button class="panel-toggle" type="button" aria-label="Collapse character sheet" aria-expanded="true">‹</button> as HTMLButtonElement;
    this.inventoryToggle = <button class="panel-toggle" type="button" aria-label="Collapse inventory" aria-expanded="true">›</button> as HTMLButtonElement;
    this.characterPanel = <aside class="character-panel">{this.characterToggle}{back}{this.sheetNode}</aside> as HTMLElement;
    this.inventoryPanel = <aside class="inventory-column">{this.inventoryToggle}{this.inventoryNode}</aside> as HTMLElement;
    this.inventoryNode.append(this.inventoryHeader, this.backpackScroll);
    this.characterToggle.onclick = () => this.togglePanel(this.characterPanel, this.characterToggle, "character", true);
    this.inventoryToggle.onclick = () => this.togglePanel(this.inventoryPanel, this.inventoryToggle, "inventory", true);
    this.resourceDock.append(<div class="health-cluster">{this.healthBar.node}{this.staminaLine}</div> as HTMLElement, <div class="xp-cluster">{this.xpToast}{this.xpBadge}</div> as HTMLElement, <div class="mana-cluster">{this.manaBar.node}</div> as HTMLElement);
    this.gameHud = <div class="game-hud"><header class="game-status-bar"><section class="hud-top">{this.realmPanel}</section></header><div class="canvas-overlay-top">{this.waveBanner}<section class="notification-area">{this.noticeNode}</section></div>{this.centerToast}{this.spellBar}{this.resourceDock}{this.characterPanel}{this.inventoryPanel}</div> as HTMLElement;
    root.append(this.joinPanel, this.publicSheet, this.gameHud); this.updateVisibility();
  }
  setJoinName(name: string): void { this.nameInput.value = name; }
  setNotice(notice: string): void { for (const node of [this.noticeNode, this.joinNoticeNode]) { node.textContent = notice; node.classList.toggle("is-hidden", !notice); } }
  showCenterToast(message: string): void { clearTimeout(this.centerToastTimer); this.centerToast.textContent = message; this.centerToast.classList.add("is-visible"); this.centerToastTimer = window.setTimeout(() => this.centerToast.classList.remove("is-visible"), 3200); }
  showXpToast(message: string): void { clearTimeout(this.xpToastTimer); this.xpToast.textContent = message; this.xpToast.classList.add("is-visible"); this.xpToastTimer = window.setTimeout(() => this.xpToast.classList.remove("is-visible"), 3200); }
  setPlayer(player: PlayerState): void { this.player = player; this.targetXp = player.progress.xp; this.displayedXp = this.displayedXp === undefined ? this.targetXp : lerpXpDisplay(this.displayedXp, this.targetXp); this.renderDynamicHud(); if (this.staticProgress !== player.progress || this.staticPlayerName !== player.name || this.staticReceivesDeathEchoes !== player.receivesDeathEchoes) { this.staticProgress = player.progress; this.staticPlayerName = player.name; this.staticReceivesDeathEchoes = player.receivesDeathEchoes; const signature = staticStateSignature(player, this.inspected); if (signature !== this.staticSignature) { this.staticSignature = signature; this.renderStaticHud(); } } if (this.lastWaveNumber !== player.waveNumber) { this.lastWaveNumber = player.waveNumber; this.renderRealm(); } this.applyPanelTriggers(player.progress); this.updateVisibility(); }
  configurePanelTriggers(triggers: { character: boolean; inventory: boolean }): void { this.panelTriggers = { ...triggers }; if (triggers.character) this.setPanelCollapsed(this.characterPanel, this.characterToggle, "character", true); if (triggers.inventory) this.setPanelCollapsed(this.inventoryPanel, this.inventoryToggle, "inventory", true); }
  setLeaderboard(heroes: HeroSummary[]): void { this.leaderboardNode.replaceChildren(...heroes.map((hero) => { const button = <button class={hero.connected ? "is-online" : "is-offline"} type="button"><strong>{rankedName(hero.username, hero.receivesDeathEchoes)}</strong><span>Level {hero.level}</span></button> as HTMLButtonElement; button.onclick = () => this.callbacks.onInspectHero(hero.id); return button; })); }
  setPublicHero(hero?: PublicHeroProfile): void { if (!hero) { this.publicSheet.classList.add("is-hidden"); return; } const stats = statsWithItemBonuses(hero.stats, hero.mainHand, hero.offHand); this.publicSheet.replaceChildren(<div class="portrait"><strong>{hero.username}</strong><small>Level {hero.level} · Best wave {hero.maxWaveReached}</small></div>, <div class="attribute-grid">{STAT_KEYS.map((key) => <span><small>{key}</small><b>{fmt(stats[key])}</b></span>)}</div>, <strong>Effective stats</strong>, effectiveStatSheet(hero.mainHand, hero.offHand, stats), <strong>Main hand</strong>, equipmentSummary(hero.mainHand, stats, "main"), <strong>Offhand</strong>, hero.offHand ? equipmentSummary(hero.offHand, stats, "off") : <small>Empty</small>, <strong>Skills</strong>, <small>{[...new Set([...hero.learnedSkills, ...hero.mainHand.skills, ...(hero.offHand?.skills ?? [])])].map((id) => SKILLS[id].label).join(", ") || "None"}</small>); this.publicSheet.classList.remove("is-hidden"); }
  clearPlayer(): void { this.player = undefined; this.realm = undefined; this.inspected = undefined; this.staticProgress = undefined; this.staticSignature = ""; this.dynamicSignature = ""; this.updateVisibility(); }
  setInspection(build?: UnitBuild, xpReward?: number): void { this.inspected = build; this.inspectedXp = build ? xpReward ?? build.xpReward : undefined; this.staticSignature = `${staticStateSignature(this.player, build)}:${this.inspectedXp ?? ""}`; this.renderStaticHud(); }
  setRealm(realm: RealmState): void { const modeChanged = this.realm?.mode !== realm.mode; this.realm = realm; this.renderRealm(); if (modeChanged && this.player) this.renderInventory(this.player.progress); }
  setSpells(spells: SpellSlot[]): void { this.currentSpells = spells; this.renderSpellSlots(); [...this.spellBar.querySelectorAll<HTMLButtonElement>(".spell-slot")].forEach((button, index) => { const spell = spells[index]; if (!spell) return; button.classList.toggle("is-disabled", Boolean(spell.disabled)); button.setAttribute("aria-pressed", String(Boolean(spell.disabled))); button.onclick = () => this.callbacks.onToggleSpell(spell.id); }); }
  private previewSpellLevels(skills?: SkillId[]): void { this.spellPreview = skills && this.player ? new Map(skills.map((id) => [id, cappedSkillLevel((this.currentSpells.find((spell) => spell.id === id)?.level ?? this.player!.progress.learnedSkillLevels[id] ?? 0) + 1)])) : undefined; this.renderSpellSlots(); }
  private renderSpellSlots(): void { const preview = this.spellPreview; const ids = new Set<SkillId>([...this.currentSpells.map((spell) => spell.id), ...(preview?.keys() ?? [])]); const spells = [...ids].map((id) => this.currentSpells.find((spell) => spell.id === id) ?? { id, label: SKILLS[id].label, level: 0, cooldown: 0, cooldownMax: 0, resource: SKILLS[id].resource }); const structure = spells.map(({ id, label, level, resource }) => `${id}:${label}:${level}:${resource}:${preview?.get(id) ?? ""}`).join("|"); if (structure !== this.spellStructureSignature) { this.spellStructureSignature = structure; this.spellNodes.clear(); this.spellBar.replaceChildren(...(spells.length ? spells.map((spell) => { const cooldown = <span class="spell-cooldown" /> as HTMLElement; this.spellNodes.set(spell.id, cooldown); const skill = SKILLS[spell.id]; const projected = preview?.get(spell.id); const levelValue: PreviewValue<number> = { currentVal: spell.level, newVal: projected === undefined ? spell.level : projected }; const shownLevel = Math.max(1, projected ?? spell.level); const changed = projected !== undefined && projected !== spell.level; const progress = this.player?.progress; const stats = progress ? statsWithItemBonuses(progress.stats, progress.mainHand, progress.offHand) : undefined; const cooldownSeconds = spell.id === "healing" ? healingCooldown(shownLevel) : progress && stats ? skillCooldown(spell.id, progress.mainHand, stats) * cooldownScale(shownLevel, derivedStats(stats).cooldownReduction) : skill.cooldown; const range = progress && stats ? skillRange(spell.id, progress.mainHand, shownLevel, stats.spirit) : skill.range; const damage = skill.damageMultiplier > 0 ? skill.damageMultiplier * spellPower(shownLevel) : 0; return <button class={`spell-slot spell-resource-${spell.resource}${changed ? projected === null || projected < spell.level ? " is-level-cost-preview" : " is-level-preview" : ""}`} type="button" aria-label={`${spell.label}, level ${formatPreviewValue(levelValue)}`}>{cooldown}<strong>{spell.label.slice(0, 2).toUpperCase()}</strong><small>Lv{formatPreviewValue(levelValue)}</small><span class="spell-tooltip" role="tooltip"><b>{skill.label}</b><span class="spell-tooltip-description">{skill.description}</span><span class="spell-tooltip-stats"><span><small>Level</small><strong>{formatPreviewValue(levelValue)}</strong></span><span><small>Resource</small><strong>{capitalize(skill.resource)}</strong></span>{damage > 0 ? <span><small>Damage</small><strong>{fmt(damage)}×</strong></span> : null}<span><small>Cooldown</small><strong>{fmt(cooldownSeconds)}s</strong></span><span><small>Range</small><strong>{range ? `${fmt(range)}px` : "Self"}</strong></span></span></span></button>; }) : [<small>No spells</small>])); } for (const spell of spells) { const ratio = spell.cooldownMax > 0 ? Math.max(0, Math.min(1, spell.cooldown / spell.cooldownMax)) : 0; this.spellNodes.get(spell.id)?.style.setProperty("height", `${ratio * 100}%`); } }
  showWaveBanner(title: string, detail: string): void { clearTimeout(this.waveTimer); (this.waveBanner.querySelector("strong") as HTMLElement).textContent = title; (this.waveBanner.querySelector("span") as HTMLElement).textContent = detail; this.waveBanner.classList.add("is-visible"); this.waveTimer = window.setTimeout(() => this.waveBanner.classList.remove("is-visible"), 3200); }
  private renderDynamicHud(): void { if (!this.player) return; const p = this.player.progress; const shownXp = this.displayedXp ?? p.xp; const shownLevel = levelForXp(shownXp);
    const into = shownXp - cumulativeXpForLevel(shownLevel); const needed = xpForNextLevel(shownLevel); const xpRatio = needed > 0 ? Math.max(0, Math.min(1, into / needed)) : 0;
    const effectiveStats = statsWithItemBonuses(p.stats, p.mainHand, p.offHand); const derived = derivedStats(effectiveStats); const equipped = [p.mainHand, p.offHand].filter(Boolean) as ItemInstance[];
    const vigorousRegen = equipped.reduce((sum, item) => { const effectiveness = itemRequirementMultiplier(item, effectiveStats); const multiplier = (item.modifiers.strengthRegenMultiplier ?? 0) * effectiveness; return sum + (multiplier > 0 ? (0.01 + multiplier * effectiveStats.strength) * effectiveness : 0); }, 0);
    const healthRegen = derived.hpRegen + vigorousRegen; const mainEffectiveness = itemRequirementMultiplier(p.mainHand, effectiveStats); const manaRegen = derived.manaRegen * (1 + (p.mainHand.modifiers.manaRegenMultiplier - 1) * mainEffectiveness);
    const signature = [this.player.health, this.player.maxHealth, healthRegen, this.player.stamina, this.player.maxStamina, this.player.mana, this.player.maxMana, manaRegen, shownXp, shownLevel, this.player.name].map(flatValue).join("|");
    if (signature !== this.dynamicSignature) { this.dynamicSignature = signature; updateResourceBar(this.healthBar, this.player.health, this.player.maxHealth, healthRegen); updateResourceBar(this.manaBar, this.player.mana, this.player.maxMana, manaRegen); const stamina = resourceRatio(this.player.stamina, this.player.maxStamina); setText(this.xpName, this.player.name); setText(this.xpLevel, String(shownLevel)); this.staminaLine.setAttribute("aria-valuemax", String(this.player.maxStamina)); this.staminaLine.setAttribute("aria-valuenow", String(this.player.stamina)); (this.staminaLine.firstElementChild as HTMLElement).style.width = `${stamina * 100}%`; this.xpBadge.style.setProperty("--xp-angle", `${xpRatio * 360}deg`); this.xpBadge.setAttribute("aria-valuemax", String(needed)); this.xpBadge.setAttribute("aria-valuenow", String(into)); }
    this.activeMainHand?.style.setProperty("--attack-progress", `${(this.inspected ? 1 : this.player.attackProgress) * 100}%`);
  }
  private renderStaticHud(): void { if (!this.player) return; const p = this.player.progress; const build = this.inspected; const stats = build?.stats ?? p.stats; const main = build?.mainHand ?? p.mainHand; const off = build?.offHand ?? p.offHand; const effectiveStats = statsWithItemBonuses(stats, main, off);
    const mainSummary = equipmentSummary(main, effectiveStats, "main"); this.activeMainHand = mainSummary;
    this.sheetNode.replaceChildren(
      <div class="portrait"><strong>{build ? build.name : rankedName(this.player.name, this.player.receivesDeathEchoes)}</strong><small>Level {build?.level ?? p.level}{build ? ` · ${fmt(this.inspectedXp ?? build.xpReward)} XP` : ""}</small></div>,
      <div class="attribute-grid">{STAT_KEYS.map((key) => <span data-stat={key}><small>{key}</small><b>{fmt(effectiveStats[key])}</b></span>)}</div>,
      this.allocationNode, <strong>Effective stats</strong>, effectiveStatSheet(main, off, effectiveStats),
      <strong>Main hand</strong>, mainSummary, <strong>Offhand</strong>, off ? equipmentSummary(off, effectiveStats, "off") : <small>Empty</small>
    );
    (this.root.querySelector(".inspect-back") as HTMLElement).classList.toggle("is-hidden", !build); this.renderAllocation();
    this.renderInventory(p); }
  private renderInventory(progress: PlayerProgress): void { const balances = { gold: progress.gold, souls: progress.souls, ...progress.scraps }; for (const [key, value] of Object.entries(balances)) { const cell = this.inventoryHeader.querySelector<HTMLElement>(`.currency-cell[data-currency="${key}"] strong`); if (cell) setText(cell, String(value)); } setText(this.inventoryCount, `Equipment ${occupiedInventorySlots(progress)}/${4 + Math.ceil(progress.level / 10)}`);
    const ordered = orderInventoryTiles(progress.inventoryTiles, progress); const existing = new Map([...this.backpackScroll.children].map((node) => [(node as HTMLElement).dataset.tileId, node as HTMLElement])); const equippedKeys = new Set([itemStackKey(progress.mainHand), progress.offHand ? itemStackKey(progress.offHand) : ""]); const statsSignature = STAT_KEYS.map((key) => progress.stats[key]).join(":"); this.previewCurrencies();
    const canSend = Boolean(this.realm);
    ordered.forEach((tile, index) => { const signature = `${tile.key}:${tile.quantity}:${Number(equippedKeys.has(tile.key))}:${statsSignature}:${Number(canSend)}`; let node = existing.get(tile.id); if (!node || node.dataset.renderSignature !== signature) { const replacement = itemTile(tile, this.callbacks, progress, (item, equipped, action) => this.previewItem(item, equipped, action), (preview) => this.previewCurrencies(preview), (skills) => this.previewSpellLevels(skills), canSend); replacement.dataset.renderSignature = signature; if (node) node.replaceWith(replacement); node = replacement; } existing.delete(tile.id); const position = this.backpackScroll.children[index]; if (position !== node) this.backpackScroll.insertBefore(node, position ?? null); }); for (const node of existing.values()) node.remove(); }
  private previewItem(item?: ItemInstance, equipped = false, action: "card" | "upgrade" = "card"): void { if (!this.player || this.inspected) return; const p = this.player.progress; if (!item) { this.previewBuild(p.mainHand, p.offHand, false); this.spellPreview = undefined; this.renderSpellSlots(); return; } let main = p.mainHand; let off = p.offHand; if (action === "upgrade") { if (item.itemKind === "weapon") main = item; else off = item; } else if (equipped) { if (itemStackKey(main) === itemStackKey(item)) main = starterClub(); else if (off && itemStackKey(off) === itemStackKey(item)) off = undefined; } else if (item.itemKind === "weapon") { main = item; if (item.hands === 2) off = undefined; } else if (main.hands === 1) off = item; this.previewBuild(main, off, true); const projected = { ...p, mainHand: main, offHand: off }; const ids = new Set<SkillId>([...this.currentSpells.map((spell) => spell.id), ...p.learnedSkills, ...main.skills, ...(off?.skills ?? [])]); this.spellPreview = new Map([...ids].map((id) => [id, effectiveSkillLevel(projected, id) || null])); this.renderSpellSlots(); }
  private previewBuild(main: ItemInstance, off: ItemInstance | undefined, highlight: boolean): void { if (!this.player) return; const p = this.player.progress; const currentStats = statsWithItemBonuses(p.stats, p.mainHand, p.offHand); const nextStats = statsWithItemBonuses(p.stats, main, off); const grid = this.sheetNode.querySelector<HTMLElement>(".attribute-grid"); for (const key of STAT_KEYS) { const node = grid?.querySelector<HTMLElement>(`[data-stat="${key}"] b`); if (!node) continue; const value = { currentVal: currentStats[key], newVal: highlight ? nextStats[key] : currentStats[key] }; setText(node, formatPreviewValue(value, fmt)); applyPreviewClass(node, previewTone(value)); } const currentMain = this.sheetNode.querySelector<HTMLElement>(".equipped-main-hand"); if (currentMain) { const replacement = equipmentSummary(highlight ? main : p.mainHand, highlight ? nextStats : currentStats, "main", highlight ? p.mainHand : undefined, highlight ? currentStats : undefined); currentMain.replaceWith(replacement); this.activeMainHand = replacement; } this.previewEffectiveStats(p.stats, main, off, highlight); }
  private previewCurrencies(preview?: CurrencyPreview): void { if (!this.player) return; const p = this.player.progress; const balances = { gold: p.gold, souls: p.souls, ...p.scraps }; for (const [key, current] of Object.entries(balances)) { const cell = this.inventoryNode.querySelector<HTMLElement>(`.currency-cell[data-currency="${key}"]`); const valueNode = cell?.querySelector<HTMLElement>("strong"); if (!cell || !valueNode) continue; const delta = preview?.[key as keyof CurrencyPreview]; const value = { currentVal: current, newVal: delta === undefined ? current : current + delta }; setText(valueNode, formatPreviewValue(value)); applyPreviewClass(cell, previewTone(value)); } }
  private previewEffectiveStats(baseStats: Stats, main: ItemInstance, off: ItemInstance | undefined, highlight: boolean): void { if (!this.player) return; const current = this.sheetNode.querySelector<HTMLElement>(".combat-stat-grid"); if (!current) return; const effective = statsWithItemBonuses(baseStats, main, off); let baseline: Array<[string, string]> | undefined; if (highlight) { const p = this.player.progress; baseline = effectiveStatRows(p.mainHand, p.offHand, statsWithItemBonuses(p.stats, p.mainHand, p.offHand)); } current.replaceWith(effectiveStatSheet(main, off, effective, baseline)); }
  private renderRealm(): void { if (!this.realm) return; const r = this.realm; const signature = [r.mode, this.player?.waveNumber ?? "", Number(r.canLeave), r.outgoingQueued, r.incomingQueued, ...r.guards.map(realmMemberSignature), "|", ...r.attackers.map(realmMemberSignature)].join(":"); if (signature === this.realmSignature) return; this.realmSignature = signature; const action = <button type="button">{r.mode === "training" ? "Enter Realm" : "Leave to Lobby"}</button> as HTMLButtonElement; action.onclick = r.mode === "training" ? this.callbacks.onEnterRealm : this.callbacks.onLeaveRealm;
    action.disabled = r.mode !== "training" && !r.canLeave; const logout = <button type="button">Logout</button> as HTMLButtonElement; logout.onclick = this.callbacks.onLogout;
    const kill = <button class="kill-player" type="button">Kill Player</button> as HTMLButtonElement; kill.onclick = this.callbacks.onKillPlayer;
    const title = r.mode === "training" ? `Wave ${this.player?.waveNumber ?? "—"} · Halls of Realms` : r.mode === "waiting" ? `Wave ${this.player?.waveNumber ?? "—"} · Waiting for realm` : `Wave ${this.player?.waveNumber ?? "—"}`;
    const members = (values: RealmState["guards"]) => values.length ? values.flatMap((p, index) => { const button = <button class="realm-member" type="button">{rankedName(`${p.name} L${p.level}${p.down ? " ↓" : ""}`, p.receivesDeathEchoes)}</button> as HTMLButtonElement; button.onclick = () => this.callbacks.onInspectHero(p.id); return [index ? document.createTextNode(", ") : null, button]; }).filter(Boolean) as Node[] : [document.createTextNode("—")];
    const guards = <span>Guard: </span> as HTMLElement; guards.append(...members(r.guards)); const attackers = <span>Attacker: </span> as HTMLElement; attackers.append(...members(r.attackers));
    this.realmPanel.replaceChildren(<strong>{title}</strong>, guards, attackers, <span>Queues {r.outgoingQueued} out / {r.incomingQueued} in</span>, action, ...(r.mode === "training" ? [logout] : [kill])); }
  private renderAllocation(): void { const signature = this.inspected ? "inspection" : this.player ? STAT_KEYS.map((key) => this.player!.progress.allocation[key]).join(":") : "none"; if (signature === this.allocationSignature) return; this.allocationSignature = signature; this.allocationNode.replaceChildren(); if (!this.player || this.inspected) { this.allocationNode.classList.add("is-hidden"); return; } this.allocationNode.classList.remove("is-hidden"); const values = integerAllocation(this.player.progress.allocation); const valueNodes = new Map<keyof Stats, HTMLElement>(); const minusButtons = new Map<keyof Stats, HTMLButtonElement>(); const plusButtons = new Map<keyof Stats, HTMLButtonElement>(); let preview = false;
    const rows = STAT_KEYS.map((key) => { const value = <b>{values[key]}</b> as HTMLElement; const minus = <button type="button" aria-label={`Decrease ${key}`}>−</button> as HTMLButtonElement; const plus = <button type="button" aria-label={`Increase ${key}`}>+</button> as HTMLButtonElement; valueNodes.set(key, value); minusButtons.set(key, minus); plusButtons.set(key, plus); return <div class="allocation-row"><span>{key}</span>{minus}{value}{plus}</div>; });
    const budget = <small class="allocation-remaining" /> as HTMLElement; const reset = <button type="button">Reset allocation</button> as HTMLButtonElement; const save = <button type="submit">Save for future levels</button> as HTMLButtonElement; const respec = <button type="button" class="allocation-respec" /> as HTMLButtonElement; const controls = <div class="allocation-controls">{rows}{budget}<div class="allocation-actions">{reset}{save}{respec}</div></div> as HTMLElement; this.allocationNode.append(<strong class="allocation-title">Next-level allocation</strong>, controls);
    const currentValues = (): Stats => ({ ...values }); const update = () => { const total = STAT_KEYS.reduce((sum, key) => sum + values[key], 0); budget.textContent = `Budget ${total}/5 · ${5 - total} remaining`; save.disabled = total !== 5; respec.disabled = total !== 5; respec.textContent = `Reapply ratio to all levels · ${this.player!.progress.level * 100}g`; for (const key of STAT_KEYS) { setText(valueNodes.get(key)!, String(values[key])); minusButtons.get(key)!.disabled = values[key] === 0; plusButtons.get(key)!.disabled = total >= 5; } const grid = this.sheetNode.querySelector<HTMLElement>(".attribute-grid"); const p = this.player!.progress; const projected = Object.fromEntries(STAT_KEYS.map((key) => [key, p.stats[key] + values[key]])) as Stats; const currentEffective = statsWithItemBonuses(p.stats, p.mainHand, p.offHand); const projectedEffective = statsWithItemBonuses(projected, p.mainHand, p.offHand); for (const key of STAT_KEYS) { const node = grid?.querySelector<HTMLElement>(`[data-stat="${key}"] b`); if (node) { const value = { currentVal: currentEffective[key], newVal: preview ? projectedEffective[key] : currentEffective[key] }; setText(node, formatPreviewValue(value, fmt)); applyPreviewClass(node, previewTone(value)); } } this.previewEffectiveStats(preview ? projected : p.stats, p.mainHand, p.offHand, preview); };
    for (const key of STAT_KEYS) { minusButtons.get(key)!.onclick = () => { values[key] = Math.max(0, values[key] - 1); update(); }; plusButtons.get(key)!.onclick = () => { if (STAT_KEYS.reduce((sum, stat) => sum + values[stat], 0) < 5) values[key] += 1; update(); }; }
    reset.onclick = () => { for (const key of STAT_KEYS) values[key] = 0; update(); }; respec.onclick = () => { if (!respec.disabled) this.callbacks.onRespec(currentValues()); }; this.allocationNode.onmouseenter = () => { preview = true; update(); }; this.allocationNode.onmouseleave = () => { if (!this.allocationNode.contains(document.activeElement)) { preview = false; update(); } }; const focusNode = this.allocationNode as HTMLElement & { onfocusin: (() => void) | null; onfocusout: (() => void) | null }; focusNode.onfocusin = () => { preview = true; update(); }; focusNode.onfocusout = () => window.setTimeout(() => { if (!this.allocationNode.contains(document.activeElement)) { preview = false; update(); } }); this.allocationNode.onsubmit = (event) => { event.preventDefault(); if (!save.disabled) this.callbacks.onAllocation(currentValues()); }; update(); }
  private applyPanelTriggers(progress: PlayerProgress): void { if (this.panelTriggers.character && progress.level >= 1) { this.panelTriggers.character = false; this.setPanelCollapsed(this.characterPanel, this.characterToggle, "character", false); this.callbacks.onDismissPanelTrigger("character"); } const itemCount = progress.inventoryTiles.reduce((sum, tile) => sum + tile.quantity, 0); if (this.panelTriggers.inventory && itemCount > 3) { this.panelTriggers.inventory = false; this.setPanelCollapsed(this.inventoryPanel, this.inventoryToggle, "inventory", false); this.callbacks.onDismissPanelTrigger("inventory"); } }
  private togglePanel(panel: HTMLElement, toggle: HTMLButtonElement, kind: "character" | "inventory", manual = false): void { if (manual && this.panelTriggers[kind]) { this.panelTriggers[kind] = false; this.callbacks.onDismissPanelTrigger(kind); } this.setPanelCollapsed(panel, toggle, kind, !panel.classList.contains("is-collapsed")); }
  private setPanelCollapsed(panel: HTMLElement, toggle: HTMLButtonElement, kind: "character" | "inventory", collapsed: boolean): void {
    panel.classList.toggle("is-collapsed", collapsed); toggle.textContent = kind === "character" ? (collapsed ? "›" : "‹") : (collapsed ? "‹" : "›"); toggle.setAttribute("aria-expanded", String(!collapsed)); toggle.setAttribute("aria-label", `${collapsed ? "Expand" : "Collapse"} ${kind === "character" ? "character sheet" : "inventory"}`);
    document.documentElement.style.setProperty(kind === "character" ? "--character-panel-width" : "--inventory-panel-width", collapsed ? "30px" : kind === "character" ? "220px" : "640px");
  }
  private updateVisibility(): void { const joined = Boolean(this.player); this.joinPanel.classList.toggle("is-hidden", joined); this.gameHud.classList.toggle("is-hidden", !joined); }
}
function equipmentSummary(item: ItemInstance, stats: Stats, slot: "main" | "off", baselineItem?: ItemInstance, baselineStats?: Stats): HTMLElement {
  const node = (
    <div class={`item-card equipped-item equipped-${slot}-hand rarity-${item.rarity}`} style={slot === "main" ? "--attack-progress:100%" : undefined}>
      <strong>{item.name}</strong><small class={baselineItem && baselineItem.level !== item.level ? "is-gain-preview" : ""}>Level {formatPreviewValue({ currentVal: baselineItem?.level ?? item.level, newVal: item.level })} · {item.itemKind === "weapon" ? `${item.hands}-handed` : item.itemKind === "buckler" ? "Buckler" : "Relic"} · {item.rarity}</small>
      {itemDetails(item, stats, baselineItem, baselineStats)}
    </div>
  ) as HTMLElement; bindRequirementPreview(node.querySelector<HTMLElement>(".equipment-details")!, item, stats); return node;
}
function effectiveStatRows(main: ItemInstance, off: ItemInstance | undefined, stats: Stats): Array<[string, string]> {
  const derived = derivedStats(stats); const items = [main, off].filter(Boolean) as ItemInstance[]; const buckler = off?.itemKind === "buckler" ? off : undefined;
  const perks = equippedPerks(stats, main, off); const mainEffectiveness = itemRequirementMultiplier(main, stats); const bucklerEffectiveness = buckler ? itemRequirementMultiplier(buckler, stats) : 1;
  const lifeSteal = items.reduce((sum, item) => { const effectiveness = itemRequirementMultiplier(item, stats); const base = (item.modifiers.lifeStealBase ?? 0) * effectiveness; return sum + (base + (base > 0 ? 0.001 * stats.spirit : 0)) * effectiveness; }, 0);
  const vigorous = items.reduce((sum, item) => { const effectiveness = itemRequirementMultiplier(item, stats); const multiplier = (item.modifiers.strengthRegenMultiplier ?? 0) * effectiveness; return sum + (multiplier > 0 ? (0.01 + multiplier * stats.strength) * effectiveness : 0); }, 0);
  return [
    ["Damage", fmt(weaponDamage(main, stats))], ["Attacks/s", fmt(weaponAttackSpeed(main, stats))], ["Attack cost", `${fmt(main.staminaCost)} stamina`], ["Attack range", `${weaponRange(main)}px`],
    ["Crit chance", percent(Math.min(1, derived.critChance + main.modifiers.critChance * mainEffectiveness))], ["Crit damage", percent(derived.critMultiplier)], ["Magic amp", percent(Math.max(0, derived.magicAmp + main.modifiers.magicAmp * mainEffectiveness - 1))], ["Cooldown reduction", percent(derived.cooldownReduction)], ["Spell range/Lv", `+${fmt(0.5 * stats.spirit)}px`], ["Spell power/Lv", "+15%"],
    ["Max health", fmt(derived.maxHp)], ["Max stamina", fmt(derived.maxStamina)], ["Max mana", fmt(derived.maxMana)], ["Defense", fmt(perks.defense + (buckler ? stats.strength : 0))], ["Dodge chance", percent(Math.min(.5, stats.agility * .003 + perks.dodgeChance))], ["Physical resist", percent(Math.min(.5, perks.physicalResist))], ["Magic resist", percent(Math.min(.5, perks.magicResist))], ["Fire resist", percent(Math.min(.5, perks.fireResist))], ["Frost resist", percent(Math.min(.5, perks.frostResist))], ["Poison resist", percent(Math.min(.5, perks.poisonResist))], ["Bleed resist", percent(Math.min(.5, perks.bleedResist))], ["Block chance", percent(bucklerBlockChance(buckler, stats))], ["Block cost", buckler ? `${fmt(bucklerBlockCost(buckler, stats))} stamina` : "0"],
    ["Health regen", `${fmt(derived.hpRegen + vigorous)}/s`], ["Mana regen", `${fmt(derived.manaRegen * (1 + (main.modifiers.manaRegenMultiplier - 1) * mainEffectiveness))}/s`], ["Stamina regen", `${fmt(derived.staminaRegen)}/s`], ["Life steal", percent(lifeSteal)],
    ["Bleed chance", percent(main.modifiers.bleedChance * mainEffectiveness)], ["Poison chance", percent(main.modifiers.poisonChance * mainEffectiveness)], ["Stun chance", percent(main.modifiers.stunChance * mainEffectiveness)], ["Gold gain", percent((buckler?.modifiers.goldGain ?? 0) * bucklerEffectiveness)], ["Rarity boost", percent((buckler?.modifiers.rarityBoost ?? 0) * bucklerEffectiveness)], ["Attraction", `${fmt(Math.max(main.attractionSpeed * mainEffectiveness, (off?.attractionSpeed ?? 0) * (off ? itemRequirementMultiplier(off, stats) : 1)))}px/s`], ["Reflection", buckler?.reflectionComponents.join(" / ") || "None"]
  ];
}
function effectiveStatSheet(main: ItemInstance, off: ItemInstance | undefined, stats: Stats, baseline?: Array<[string, string]>): HTMLElement {
  const previous = new Map(baseline); const rows = effectiveStatRows(main, off, stats);
  return <div class={`combat-stat-grid${baseline ? " is-previewing" : ""}`}>{rows.map(([label, newValue]) => { const currentVal = previous.get(label) ?? newValue; const changed = Boolean(baseline && currentVal !== newValue); const lowerIsBetter = label === "Attack cost" || label === "Block cost"; const currentNumber = Number.parseFloat(currentVal); const newNumber = Number.parseFloat(newValue); const tone = !changed ? "same" : Number.isFinite(currentNumber) && Number.isFinite(newNumber) ? previewTone({ currentVal: currentNumber, newVal: newNumber }, !lowerIsBetter) : "gain"; return <span><small>{label}</small><b class={tone === "gain" ? "is-gain-preview" : tone === "cost" ? "is-cost-preview" : ""}>{formatPreviewValue({ currentVal, newVal: baseline ? newValue : currentVal })}</b></span>; })}</div> as HTMLElement;
}
function currencyCell(label: string, value: number, kind: string): HTMLElement { return <div class={`currency-cell currency-${kind}`} data-currency={kind}><small>{label}</small><strong>{value}</strong></div> as HTMLElement; }
interface ResourceBar { node: HTMLElement; value: HTMLElement; regen: HTMLElement; fill: HTMLElement; loss: HTMLElement; previous?: number; lossTimer?: ReturnType<typeof setTimeout> }
function resourceBar(label: string, kind: "health" | "mana"): ResourceBar { const value = <span /> as HTMLElement; const regen = <span class="resource-regen" /> as HTMLElement; const loss = <span class="resource-loss" /> as HTMLElement; const fill = <span class="resource-fill" /> as HTMLElement; const node = <div class={`resource-bar resource-${kind}`} role="progressbar" aria-label={label} aria-valuemin="0"><div class="resource-bar-header"><strong>{label}</strong><span class="resource-bar-values">{value}{regen}</span></div><div class="resource-bar-track">{loss}{fill}</div></div> as HTMLElement; return { node, value, regen, fill, loss }; }
function updateResourceBar(bar: ResourceBar, current: number, maximum: number, regen: number): void { const safeMaximum = Math.max(0, maximum); const safeCurrent = Math.max(0, Math.min(current, safeMaximum)); const ratio = resourceRatio(safeCurrent, safeMaximum); const previous = bar.previous; bar.node.setAttribute("aria-valuemax", String(safeMaximum)); bar.node.setAttribute("aria-valuenow", String(safeCurrent)); setText(bar.value, `${fmt(safeCurrent)} / ${fmt(safeMaximum)}`); setText(bar.regen, `+${fmt(Math.max(0, regen))}/s`); bar.fill.style.width = `${ratio * 100}%`; if (previous === undefined || safeCurrent >= previous) { if (bar.lossTimer) clearTimeout(bar.lossTimer); bar.lossTimer = undefined; bar.loss.classList.remove("is-catching-up"); bar.loss.style.width = `${ratio * 100}%`; } else { bar.loss.classList.remove("is-catching-up"); if (bar.lossTimer) clearTimeout(bar.lossTimer); bar.lossTimer = setTimeout(() => { bar.loss.classList.add("is-catching-up"); bar.loss.style.width = `${ratio * 100}%`; bar.lossTimer = undefined; }, 420); } bar.previous = safeCurrent; }
function resourceRatio(current: number, maximum: number): number { return maximum > 0 ? Math.max(0, Math.min(1, current / maximum)) : 0; }
function flatValue(value: string | number): string { return typeof value === "number" ? String(Math.round(value * 100) / 100) : value; }
function setText(node: HTMLElement, value: string): void { if (node.textContent !== value) node.textContent = value; }
function staticStateSignature(player: PlayerState | undefined, inspected: UnitBuild | undefined): string { if (!player) return "none"; const p = player.progress; return [player.name, Number(player.receivesDeathEchoes), p.level, inspected?.id ?? "hero", inspected?.level ?? "", p.gold, p.souls, ...Object.values(p.scraps), ...STAT_KEYS.map((key) => (inspected?.stats ?? p.stats)[key]), itemStackKey(inspected?.mainHand ?? p.mainHand), inspected?.offHand ? itemStackKey(inspected.offHand) : p.offHand ? itemStackKey(p.offHand) : "", ...p.inventoryTiles.map((tile) => `${tile.id}:${tile.key}:${tile.quantity}`)].join("|"); }
function realmMemberSignature(member: RealmState["guards"][number]): string { return `${member.id},${member.name},${member.level},${Number(member.down)},${Number(member.receivesDeathEchoes)}`; }
function rankedName(name: string, receivesDeathEchoes: boolean): Node { if (!receivesDeathEchoes) return document.createTextNode(name); const warning = <span class="death-echo-warning" tabindex="0" aria-label="Highest-ranked hero: receives all other players' death echoes in this realm to fight against">⚠<span role="tooltip">Highest-ranked hero: receives all other players' death echoes in this realm to fight against.</span></span> as HTMLElement; const wrapper = <span class="ranked-name">{warning}{name}</span> as HTMLElement; return wrapper; }
function capitalize(value: string): string { return `${value.charAt(0).toUpperCase()}${value.slice(1)}`; }
function fmt(value: number): string { return Number.isInteger(value) ? String(value) : value.toFixed(1); }
function percent(value: number): string { return `${fmt(value * 100)}%`; }
