import type { SkillId } from "./items";

/** Short player-facing acquisition labels derived from specs/spells/*.md. */
export const SPELL_SOURCES: Readonly<Record<SkillId, string>> = {
	bash: "Club",
	sweep: "Sword",
	flurry: "Dagger",
	shockwave: "Mace",
	cleave: "Axe",
	whirlwind: "Rare or Epic Axe",
	rendingThrow: "Throwing Axe",
	vampiricBoomerang: "Charm",
	orbitingHammers: "Hammer",
	arcaneBolt: "Staff",
	gravityPull: "Attraction Idol relic",
	attraction: "Attraction Idol; some Staves, Relics, Amulets, and Charms",
	manaDrain: "Spirit Wounds Idol relic",
	penance: "Penance Idol relic",
	thorns: "Rare or Epic Spiked Buckler",
	reflectiveSurge: "Rare or Epic Spiked Buckler",
	frostOrb: "Rare or Epic Staff",
	blizzard: "Rare, Epic, or Unique Staff",
	fireBreath: "Ember Idol relic",
	swamp: "Voodoo Doll relic",
	rapidRegen: "Renewal Idol relic",
	voodoo: "Voodoo Doll relic",
	healing: "New-hero skill; Rare or Epic Mace",
	rent: "Universal learned skill",
	blocking: "Buckler",
	slowAura: "Scepter or qualifying Holy Buckler",
	hinderingAura: "Scepter or qualifying Holy Buckler",
	deathBurst: "Scepter or qualifying Holy Buckler",
	sunburnAura: "Scepter or qualifying Holy Buckler",
	thunderAura: "Scepter or qualifying Holy Buckler",
	timeHarvest: "Amulet",
};
